---
format:
  html:
    toc: true
    toc-depth: 5
    theme: [cosmo, ../../clay/custom.scss]
    toc-location: right
    anchor-sections: true
    reference-location: margin
    fontsize: 0.9em
    output-file: easings.html
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="easings_files/md-default0.js" type="text/javascript"></script><script src="easings_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns easings
  (:require [fastmath.easings :as easings]
            [fastmath.dev.codox :as codox]))
```
:::



# Easings {.unnumbered}


## Reference

### fastmath.easings

Easing functions.

  List of all are in [easings-list](#LOS-easings-list).


```{=html}
<span id="#LOS-back-in"></span>
```


#### back-in

+ `(back-in t)`
+ `(back-in s t)`

BackIn easing.

  Parameter `s` (default: 1.70158) defines overshoot.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L28">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-back-in-out"></span>
```


#### back-in-out

+ `(back-in-out t)`
+ `(back-in-out s t)`

BackInOut easing.

  Parameter `s` (default: 1.70158) defines overshoot.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L47">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-back-out"></span>
```


#### back-out

+ `(back-out t)`
+ `(back-out s t)`

BackOut easing.

  Parameter `s` (default: 1.70158) defines overshoot.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L37">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-bounce-in"></span>
```


#### bounce-in

+ `(bounce-in t)`

BounceIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L83">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-bounce-in-out"></span>
```


#### bounce-in-out

+ `(bounce-in-out t)`

BounceInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L89">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-bounce-out"></span>
```


#### bounce-out

+ `(bounce-out t)`

BounceOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L73">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-circle-in"></span>
```


#### circle-in

+ `(circle-in t)`

CircleIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L100">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-circle-in-out"></span>
```


#### circle-in-out

+ `(circle-in-out t)`

CircleInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L113">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-circle-out"></span>
```


#### circle-out

+ `(circle-out t)`

CircleIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L106">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cubic-in"></span>
```


#### cubic-in

+ `(cubic-in t)`

CubicIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L125">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cubic-in-out"></span>
```


#### cubic-in-out

+ `(cubic-in-out t)`

CubicInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L138">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cubic-out"></span>
```


#### cubic-out

+ `(cubic-out t)`

CubicOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L131">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-easings-list"></span>
```


#### easings-list

Map of easing names (as keywords) and functions.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L339">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-elastic-in"></span>
```


#### elastic-in

+ `(elastic-in t)`
+ `(elastic-in amplitude period)`

ElasticIn.

  When called with `t` parameter, returns easing value (for `amplitude=1.0` and `period=0.3`).
  When called with `amplitude` and `period` returns custom easing function.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L159">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-elastic-in-out"></span>
```


#### elastic-in-out

+ `(elastic-in-out t)`
+ `(elastic-in-out amplitude period)`

ElasticInOut.

  When called with `t` parameter, returns easing value (for `amplitude=1.0` and `period=0.3`).
  When called with `amplitude` and `period` returns custom easing function.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L189">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-elastic-out"></span>
```


#### elastic-out

+ `(elastic-out t)`
+ `(elastic-out amplitude period)`

ElasticOut.

  When called with `t` parameter, returns easing value (for `amplitude=1.0` and `period=0.3`).
  When called with `amplitude` and `period` returns custom easing function.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L175">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-exp-in"></span>
```


#### exp-in

+ `(exp-in t)`

ExpIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L211">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-exp-in-out"></span>
```


#### exp-in-out

+ `(exp-in-out t)`

ExpInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L223">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-exp-out"></span>
```


#### exp-out

+ `(exp-out t)`

ExpOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L217">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-in-out"></span>
```


#### in-out

+ `(in-out easeing)`

Create in-out easing for given `easing` function.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L320">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-linear"></span>
```


#### linear

+ `(linear t)`

Linear easing (identity)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L24">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-out"></span>
```


#### out

+ `(out easeing)`

Create out easing for given `easing` function.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L314">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-poly-in"></span>
```


#### poly-in

+ `(poly-in t)`
+ `(poly-in e t)`

PolyIn easing.

  Optional exponent `e` defaults to 3.0.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L234">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-poly-in-out"></span>
```


#### poly-in-out

+ `(poly-in-out t)`
+ `(poly-in-out e t)`

PolyInOut easing.

  Optional exponent `e` defaults to 3.0.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L250">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-poly-out"></span>
```


#### poly-out

+ `(poly-out t)`
+ `(poly-out e t)`

PolyOut easing.

  Optional exponent `e` defaults to 3.0.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L242">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-quad-in"></span>
```


#### quad-in

+ `(quad-in t)`

QuadIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L268">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-quad-in-out"></span>
```


#### quad-in-out

+ `(quad-in-out t)`

QuadInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L280">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-quad-out"></span>
```


#### quad-out

+ `(quad-out t)`

QuadOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L274">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-reflect"></span>
```


#### reflect

+ `(reflect easing center)`

Create in-out easing for given `easing` function and `center`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L328">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sin-in"></span>
```


#### sin-in

+ `(sin-in t)`

SinIn easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L293">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sin-in-out"></span>
```


#### sin-in-out

+ `(sin-in-out t)`

SinInOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L305">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sin-out"></span>
```


#### sin-out

+ `(sin-out t)`

SinOut easing


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/easings.clj#L299">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/generateme/fastmath//blob/master/clay/easings.clj">clay/easings.clj</a></small></small></pre></div>
```
