
---
format:
  html:
    toc: true
    toc-depth: 5
    theme: [cosmo, ../../clay/custom.scss]
    toc-location: right
    anchor-sections: true
    reference-location: margin
    fontsize: 0.9em
    output-file: vector_matrix.html
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="vector_matrix_files/md-default0.js" type="text/javascript"></script><script src="vector_matrix_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns vector-matrix
  (:require [fastmath.vector :as v]
            [fastmath.matrix :as mat]
            [fastmath.dev.codox :as codox]))
```
:::



# Vectors and matrices {.unnumbered}


## Vectors


### Reference

#### fastmath.vector

Mathematical vector operations.

  ### Types

  * Fixed size (custom types):
      * Number - 1d vector
      * Vec2 - 2d vector, creator [vec2](#LOS-vec2)
      * Vec3 - 3d vector, creator [vec3](#LOS-vec3)
      * Vec4 - 4d vector, creator [vec4](#LOS-vec4)
      * ArrayVec - fixed size double array wrapper, n-dimensional, creator [array-vec](#LOS-array-vec)
  * Fixed size
      * doubles - double array itself
  * Variable size:
      * Clojure's IPersistentVector, creator `[]`
      * Clojure's ISeq

  [VectorProto](#LOS-VectorProto) defines most of the functions.

  Vectors implements also:

  * `Sequable`
  * `Sequencial`
  * `IFn`
  * `Counted`
  * `Reversible`
  * `Indexed`
  * `ILookup`
  * `equals` and `toString` from `Object`
  * `IPersistentVector`
  * `Associative`
  * `clojure.core.matrix.protocols`
  * `IReduce` and `IReduceInit`

  That means that vectors can be destructured, treated as sequence or called as a function. See [vec2](#LOS-vec2) for examples.


```{=html}
<span id="#LOS--&gt;ArrayVec"></span>
```


##### ->ArrayVec

+ `(->ArrayVec array)`

Positional factory function for class fastmath.vector.ArrayVec.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L254">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS--&gt;Vec2"></span>
```


##### ->Vec2

+ `(->Vec2 x y)`

Positional factory function for class fastmath.vector.Vec2.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L718">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS--&gt;Vec3"></span>
```


##### ->Vec3

+ `(->Vec3 x y z)`

Positional factory function for class fastmath.vector.Vec3.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L514">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS--&gt;Vec4"></span>
```


##### ->Vec4

+ `(->Vec4 x y z w)`

Positional factory function for class fastmath.vector.Vec4.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L392">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-abs"></span>
```


##### abs

+ `(abs v)`

Absolute value of vector elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L943">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acos"></span>
```


##### acos

+ `(acos vector)`

Apply acos to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acosh"></span>
```


##### acosh

+ `(acosh vector)`

Apply acosh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acot"></span>
```


##### acot

+ `(acot vector)`

Apply acot to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acoth"></span>
```


##### acoth

+ `(acoth vector)`

Apply acoth to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acsc"></span>
```


##### acsc

+ `(acsc vector)`

Apply acsc to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acsch"></span>
```


##### acsch

+ `(acsch vector)`

Apply acsch to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-add"></span>
```


##### add

+ `(add v)`
+ `(add v1 v2)`

Sum of two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L920">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-aligned?"></span>
```


##### aligned?

+ `(aligned? v1 v2 tol)`
+ `(aligned? v1 v2)`

Are vectors aligned (have the same direction)?


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1251">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-angle-between"></span>
```


##### angle-between

+ `(angle-between v1 v2)`

Angle between two vectors

  See also [relative-angle-between](#LOS-relative-angle-between).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1230">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-applyf"></span>
```


##### applyf ^~DEPRECATED~^

*Deprecated: v1.3.0*

Same as [fmap](#LOS-fmap). Deprecated.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L847">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-approx"></span>
```


##### approx

+ `(approx v)`
+ `(approx v d)`

Round to 2 (or `d`) decimal places


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L896">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-array-&gt;vec2"></span>
```


##### array->vec2

+ `(array->vec2 arr)`

Doubles array to Vec2


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1291">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-array-&gt;vec3"></span>
```


##### array->vec3

+ `(array->vec3 arr)`

Doubles array to Vec3


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1296">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-array-&gt;vec4"></span>
```


##### array->vec4

+ `(array->vec4 arr)`

Doubles array to Vec4


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1301">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-array-vec"></span>
```


##### array-vec

+ `(array-vec xs)`

Make ArrayVec type based on provided sequence `xs`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1093">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-as-vec"></span>
```


##### as-vec

+ `(as-vec v)`
+ `(as-vec v xs)`

Create vector from sequence as given type. If there is no sequence fill with `0.0`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L874">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asec"></span>
```


##### asec

+ `(asec vector)`

Apply asec to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asech"></span>
```


##### asech

+ `(asech vector)`

Apply asech to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asin"></span>
```


##### asin

+ `(asin vector)`

Apply asin to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asinh"></span>
```


##### asinh

+ `(asinh vector)`

Apply asinh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-atan"></span>
```


##### atan

+ `(atan vector)`

Apply atan to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-atanh"></span>
```


##### atanh

+ `(atanh vector)`

Apply atanh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-average"></span>
```


##### average

+ `(average v)`
+ `(average v weights)`

Mean or weighted average of the vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1144">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-average-vectors"></span>
```


##### average-vectors

+ `(average-vectors init vs)`
+ `(average-vectors vs)`

Average / centroid of vectors. Input: initial vector (optional), list of vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1138">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-axis-rotate"></span>
```


##### axis-rotate

+ `(axis-rotate v angle axis)`
+ `(axis-rotate v angle axis pivot)`

Rotate vector. Only for `Vec3` types


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1042">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-base-from"></span>
```


##### base-from

+ `(base-from v)`

List of perpendicular vectors (basis). Works only for `Vec2` and `Vec3` types.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L971">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cb"></span>
```


##### cb

+ `(cb vector)`

Apply cb to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cbrt"></span>
```


##### cbrt

+ `(cbrt vector)`

Apply cbrt to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ceil"></span>
```


##### ceil

+ `(ceil vector)`

Apply ceil to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-clamp"></span>
```


##### clamp

+ `(clamp v mn mx)`
+ `(clamp v)`

Clamp elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1128">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cos"></span>
```


##### cos

+ `(cos vector)`

Apply cos to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cosh"></span>
```


##### cosh

+ `(cosh vector)`

Apply cosh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cot"></span>
```


##### cot

+ `(cot vector)`

Apply cot to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-coth"></span>
```


##### coth

+ `(coth vector)`

Apply coth to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cross"></span>
```


##### cross

+ `(cross v1 v2)`

Cross product


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1033">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-csc"></span>
```


##### csc

+ `(csc vector)`

Apply csc to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-csch"></span>
```


##### csch

+ `(csch vector)`

Apply csch to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-degrees"></span>
```


##### degrees

+ `(degrees vector)`

Apply degrees to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-delta-eq"></span>
```


##### delta-eq

+ `(delta-eq v1 v2)`
+ `(delta-eq v1 v2 abs-tol)`
+ `(delta-eq v1 v2 abs-tol rel-tol)`

Equality with given absolute (and/or relative) toleance.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L901">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dhash-code"></span>
```


##### dhash-code

+ `(dhash-code state a)`
+ `(dhash-code a)`

double hashcode


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L374">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist"></span>
```


##### dist

+ `(dist v1 v2)`

Euclidean distance between vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1149">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-abs"></span>
```


##### dist-abs

+ `(dist-abs v1 v2)`

Manhattan distance between vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1159">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-ang"></span>
```


##### dist-ang

+ `(dist-ang v1 v2)`

Angular distance


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1189">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-canberra"></span>
```


##### dist-canberra

+ `(dist-canberra v1 v2)`

Canberra distance


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1174">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-cheb"></span>
```


##### dist-cheb

+ `(dist-cheb v1 v2)`

Chebyshev distance between 2d vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1164">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-discrete"></span>
```


##### dist-discrete

+ `(dist-discrete v1 v2)`

Discrete distance between 2d vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1169">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-emd"></span>
```


##### dist-emd

+ `(dist-emd v1 v2)`

Earth Mover's Distance


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1181">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dist-sq"></span>
```


##### dist-sq

+ `(dist-sq v1 v2)`

Squared Euclidean distance between vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1154">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-distances"></span>
```


##### distances


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1201">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-div"></span>
```


##### div

+ `(div v1 v)`
+ `(div v1)`

Vector division or reciprocal.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1113">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-dot"></span>
```


##### dot

+ `(dot v1 v2)`

Dot product of two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L916">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-econstrain"></span>
```


##### econstrain

+ `(econstrain v mn mx)`

Element-wise constrain


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1005">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-edelta-eq"></span>
```


##### edelta-eq

+ `(edelta-eq v1 v2)`
+ `(edelta-eq v1 v2 abs-tol)`
+ `(edelta-eq v1 v2 abs-tol rel-tol)`

Element-wise equality with given absolute (and/or relative) toleance.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L907">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ediv"></span>
```


##### ediv

+ `(ediv v1 v2)`

Element-wise division of two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1118">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-einterpolate"></span>
```


##### einterpolate

+ `(einterpolate v1 v2 v)`
+ `(einterpolate v1 v2 v f)`

Interpolate vector selement-wise, optionally set interpolation fn (default: lerp)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1000">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-emn"></span>
```


##### emn

+ `(emn v1 v2)`

Element-wise min from two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L959">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-emult"></span>
```


##### emult

+ `(emult v1 v2)`

Element-wise vector multiplication (Hadamard product).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L939">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-emx"></span>
```


##### emx

+ `(emx v1 v2)`

Element-wise max from two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L955">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-exp"></span>
```


##### exp

+ `(exp vector)`

Apply exp to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-expm1"></span>
```


##### expm1

+ `(expm1 vector)`

Apply expm1 to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-faceforward"></span>
```


##### faceforward

+ `(faceforward n v)`

Flip normal `n` to match the same direction as `v`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1258">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-floor"></span>
```


##### floor

+ `(floor vector)`

Apply floor to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-fmap"></span>
```


##### fmap

+ `(fmap v f)`

Apply function to all vector values (like map but returns the same type).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L883">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-frac"></span>
```


##### frac

+ `(frac vector)`

Apply frac to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-from-polar"></span>
```


##### from-polar

+ `(from-polar v)`

From polar coordinates (2d, 3d only)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1061">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-generate-vec2"></span>
```


##### generate-vec2

+ `(generate-vec2 f1 f2)`
+ `(generate-vec2 f)`

Generate Vec2 with fn(s)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1270">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-generate-vec3"></span>
```


##### generate-vec3

+ `(generate-vec3 f1 f2 f3)`
+ `(generate-vec3 f)`

Generate Vec3 with fn(s)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1277">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-generate-vec4"></span>
```


##### generate-vec4

+ `(generate-vec4 f1 f2 f3 f4)`
+ `(generate-vec4 f)`

Generate Vec4 with fn(s)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1284">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-heading"></span>
```


##### heading

+ `(heading v)`

Angle between vector and unit vector `[1,0,...]`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1029">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-interpolate"></span>
```


##### interpolate

+ `(interpolate v1 v2 t)`
+ `(interpolate v1 v2 t f)`

Interpolate vectors, optionally set interpolation fn (default: lerp)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L991">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-is-near-zero?"></span>
```


##### is-near-zero?

+ `(is-near-zero? v)`
+ `(is-near-zero? v abs-tol)`
+ `(is-near-zero? v abs-tol rel-tol)`

Equality to zero `0` with given absolute (and/or relative) toleance.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1017">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-is-zero?"></span>
```


##### is-zero?

+ `(is-zero? v)`

Is vector zero?


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1009">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-lerp"></span>
```


##### lerp

+ `(lerp v1 v2 t)`

Linear interpolation of vectors


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L996">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-limit"></span>
```


##### limit

+ `(limit v len)`

Limit length of the vector by given value


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1223">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ln"></span>
```


##### ln

+ `(ln vector)`

Apply ln to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log"></span>
```


##### log

+ `(log vector)`

Apply log to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log10"></span>
```


##### log10

+ `(log10 vector)`

Apply log10 to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1mexp"></span>
```


##### log1mexp

+ `(log1mexp vector)`

Apply log1mexp to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1p"></span>
```


##### log1p

+ `(log1p vector)`

Apply log1p to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1pexp"></span>
```


##### log1pexp

+ `(log1pexp vector)`

Apply log1pexp to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1pmx"></span>
```


##### log1pmx

+ `(log1pmx vector)`

Apply log1pmx to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1psq"></span>
```


##### log1psq

+ `(log1psq vector)`

Apply log1psq to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log2"></span>
```


##### log2

+ `(log2 vector)`

Apply log2 to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logexpm1"></span>
```


##### logexpm1

+ `(logexpm1 vector)`

Apply logexpm1 to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logit"></span>
```


##### logit

+ `(logit vector)`

Apply logit to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logmeanexp"></span>
```


##### logmeanexp

+ `(logmeanexp v)`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1358">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logmxp1"></span>
```


##### logmxp1

+ `(logmxp1 vector)`

Apply logmxp1 to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logsoftmax"></span>
```


##### logsoftmax

+ `(logsoftmax v)`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1347">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logsumexp"></span>
```


##### logsumexp

+ `(logsumexp v)`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1353">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mag"></span>
```


##### mag

+ `(mag v)`

Length of the vector.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L892">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-magsq"></span>
```


##### magsq

+ `(magsq v)`

Length of the vector squared.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L888">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-make-vector"></span>
```


##### make-vector

+ `(make-vector dims xs)`
+ `(make-vector dims)`

Returns fixed size vector for given number of dimensions.

  Proper type is used.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1098">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-maxdim"></span>
```


##### maxdim

+ `(maxdim v)`

Index of maximum value.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L963">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mindim"></span>
```


##### mindim

+ `(mindim v)`

Index of minimum value.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L967">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mn"></span>
```


##### mn

+ `(mn v)`

Minimum value of vector elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L951">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mult"></span>
```


##### mult

+ `(mult v x)`

Multiply vector by number `x`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L935">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mx"></span>
```


##### mx

+ `(mx v)`

Maximum value of vector elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L947">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-near-zero?"></span>
```


##### near-zero?

+ `(near-zero? v)`
+ `(near-zero? v abs-tol)`
+ `(near-zero? v abs-tol rel-tol)`

Equality to zero `0` with given absolute (and/or relative) toleance.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1023">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-nonzero-count"></span>
```


##### nonzero-count

+ `(nonzero-count v)`

Count non zero velues in vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1133">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-normalize"></span>
```


##### normalize

+ `(normalize v)`

Normalize vector (set length = 1.0)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1210">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-orthogonal-polynomials"></span>
```


##### orthogonal-polynomials

+ `(orthogonal-polynomials xs)`

Creates orthogonal list of vectors based on `xs`, starting from degree 1


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1367">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-orthonormal-polynomials"></span>
```


##### orthonormal-polynomials

+ `(orthonormal-polynomials xs)`

Creates orthonormal list of vector based on `xs`, starting from degree 1


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1385">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-permute"></span>
```


##### permute

+ `(permute v idxs)`

Permute vector elements with given indices.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L983">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-perpendicular"></span>
```


##### perpendicular

+ `(perpendicular v)`
+ `(perpendicular v1 v2)`

Perpendicular vector. Only for `Vec2` and `Vec3` types.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1047">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-prod"></span>
```


##### prod

+ `(prod v)`

Product of elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L979">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-project"></span>
```


##### project

+ `(project v1 v2)`

Project `v1` onto `v2`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1265">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-radians"></span>
```


##### radians

+ `(radians vector)`

Apply radians to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-reciprocal"></span>
```


##### reciprocal

+ `(reciprocal v)`

Reciprocal of elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L987">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-relative-angle-between"></span>
```


##### relative-angle-between

+ `(relative-angle-between v1 v2)`

Angle between two vectors relative to each other.

  See also [angle-between](#LOS-angle-between).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1244">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rint"></span>
```


##### rint

+ `(rint vector)`

Apply rint to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotate"></span>
```


##### rotate

+ `(rotate v angle)`
+ `(rotate v angle-x angle-y angle-z)`

Rotate vector. Only for `Vec2` and `Vec3` types.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1037">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-round"></span>
```


##### round

+ `(round vector)`

Apply round to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-safe-sqrt"></span>
```


##### safe-sqrt

+ `(safe-sqrt vector)`

Apply safe-sqrt to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sec"></span>
```


##### sec

+ `(sec vector)`

Apply sec to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sech"></span>
```


##### sech

+ `(sech vector)`

Apply sech to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-seq-&gt;vec2"></span>
```


##### seq->vec2

+ `(seq->vec2 xs)`

Any seq to Vec2


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1306">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-seq-&gt;vec3"></span>
```


##### seq->vec3

+ `(seq->vec3 xs)`

Any seq to Vec3


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1311">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-seq-&gt;vec4"></span>
```


##### seq->vec4

+ `(seq->vec4 xs)`

Any seq to Vec4


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1316">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-set-mag"></span>
```


##### set-mag

+ `(set-mag v len)`

Set length of the vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1218">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sfrac"></span>
```


##### sfrac

+ `(sfrac vector)`

Apply sfrac to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sgn"></span>
```


##### sgn

+ `(sgn vector)`

Apply sgn to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-shift"></span>
```


##### shift

+ `(shift v)`
+ `(shift v x)`

Add value to every vector element.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L930">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sigmoid"></span>
```


##### sigmoid

+ `(sigmoid vector)`

Apply sigmoid to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-signum"></span>
```


##### signum

+ `(signum vector)`

Apply signum to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sim-cos"></span>
```


##### sim-cos

+ `(sim-cos v1 v2)`

Cosine similarity


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1194">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sin"></span>
```


##### sin

+ `(sin vector)`

Apply sin to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sinc"></span>
```


##### sinc

+ `(sinc vector)`

Apply sinc to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sinh"></span>
```


##### sinh

+ `(sinh vector)`

Apply sinh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-size"></span>
```


##### size

+ `(size v)`

Length of the vector.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L879">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-softmax"></span>
```


##### softmax

+ `(softmax v)`


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1341">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sq"></span>
```


##### sq

+ `(sq vector)`

Apply sq to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sqrt"></span>
```


##### sqrt

+ `(sqrt vector)`

Apply sqrt to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sub"></span>
```


##### sub

+ `(sub v)`
+ `(sub v1 v2)`

Subtraction of two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L925">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sum"></span>
```


##### sum

+ `(sum v)`

Sum of elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L975">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tan"></span>
```


##### tan

+ `(tan vector)`

Apply tan to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tanh"></span>
```


##### tanh

+ `(tanh vector)`

Apply tanh to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-to-polar"></span>
```


##### to-polar

+ `(to-polar v)`

To polar coordinates (2d, 3d only), first element is length, the rest angle.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1057">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-to-vec"></span>
```


##### to-vec ^~DEPRECATED~^

*Deprecated: v1.5.0*

Same as [vec->Vec](#LOS-vec->Vec). Deprecated.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L848">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-transform"></span>
```


##### transform

+ `(transform v o vx vy)`
+ `(transform v o vx vy vz)`

Transform vector; map point to coordinate system defined by origin, vx and vy (as bases), Only for `Vec2` and `Vec3` types.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1052">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-triple-product"></span>
```


##### triple-product

+ `(triple-product a b c)`

a o (b x c)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1065">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-trunc"></span>
```


##### trunc

+ `(trunc vector)`

Apply trunc to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec-&gt;RealVector"></span>
```


##### vec->RealVector

+ `(vec->RealVector v)`

Convert to Apache Commons Math RealVector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L864">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec-&gt;Vec"></span>
```


##### vec->Vec

+ `(vec->Vec v)`

Convert to Clojure primitive vector `Vec`.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L869">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec-&gt;array"></span>
```


##### vec->array

+ `(vec->array v)`

Convert to double array


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L852">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec-&gt;seq"></span>
```


##### vec->seq

+ `(vec->seq v)`

Convert to sequence (same as seq)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L856">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec2"></span>
```


##### vec2

+ `(vec2 x y)`
+ `(vec2 [x y])`
+ `(vec2)`

Make 2d vector.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1072">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec3"></span>
```


##### vec3

+ `(vec3 x y z)`
+ `(vec3 v z)`
+ `(vec3 [x y z])`
+ `(vec3)`

Make Vec2 vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1078">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vec4"></span>
```


##### vec4

+ `(vec4 x y z w)`
+ `(vec4 v w)`
+ `(vec4 v z w)`
+ `(vec4 [x y z w])`
+ `(vec4)`

Make Vec4 vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1085">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-xlogx"></span>
```


##### xlogx

+ `(xlogx vector)`

Apply xlogx to vector elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1334">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-zero-count"></span>
```


##### zero-count

+ `(zero-count v)`

Count zeros in vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1123">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-zero?"></span>
```


##### zero?

+ `(zero? v)`

Is vector zero?


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/vector.clj#L1013">source</a></small><hr style="margin: 0" /></div>
```



## Matrices {.unnumbered}


### Reference

#### fastmath.matrix

Fixed size (2x2, 3x3, 4x4) matrix types.


```{=html}
<span id="#LOS--&gt;Mat2x2"></span>
```


##### ->Mat2x2

+ `(->Mat2x2 a00 a01 a10 a11)`

Positional factory function for class fastmath.matrix.Mat2x2.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L72">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS--&gt;Mat3x3"></span>
```


##### ->Mat3x3

+ `(->Mat3x3 a00 a01 a02 a10 a11 a12 a20 a21 a22)`

Positional factory function for class fastmath.matrix.Mat3x3.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L195">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS--&gt;Mat4x4"></span>
```


##### ->Mat4x4

+ `(->Mat4x4 a00 a01 a02 a03 a10 a11 a12 a13 a20 a21 a22 a23 a30 a31 a32 a33)`

Positional factory function for class fastmath.matrix.Mat4x4.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L349">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acos"></span>
```


##### acos

+ `(acos vector)`

Apply acos to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acosh"></span>
```


##### acosh

+ `(acosh vector)`

Apply acosh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acot"></span>
```


##### acot

+ `(acot vector)`

Apply acot to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acoth"></span>
```


##### acoth

+ `(acoth vector)`

Apply acoth to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acsc"></span>
```


##### acsc

+ `(acsc vector)`

Apply acsc to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-acsch"></span>
```


##### acsch

+ `(acsch vector)`

Apply acsch to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-add"></span>
```


##### add

+ `(add A)`
+ `(add A B)`

Add matrices, C=A+B.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L985">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-adds"></span>
```


##### adds

+ `(adds A s)`

Add scalar to all matrix elements


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L990">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asec"></span>
```


##### asec

+ `(asec vector)`

Apply asec to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asech"></span>
```


##### asech

+ `(asech vector)`

Apply asech to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asin"></span>
```


##### asin

+ `(asin vector)`

Apply asin to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-asinh"></span>
```


##### asinh

+ `(asinh vector)`

Apply asinh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-atan"></span>
```


##### atan

+ `(atan vector)`

Apply atan to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-atanh"></span>
```


##### atanh

+ `(atanh vector)`

Apply atanh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cb"></span>
```


##### cb

+ `(cb vector)`

Apply cb to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cbrt"></span>
```


##### cbrt

+ `(cbrt vector)`

Apply cbrt to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ceil"></span>
```


##### ceil

+ `(ceil vector)`

Apply ceil to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cholesky"></span>
```


##### cholesky

+ `(cholesky A)`
+ `(cholesky A upper?)`

Calculate L (lower by default) triangular for where L * L^T = A.

  Checks only for symmetry, can return NaNs when A is not positive-definite.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1039">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-col"></span>
```


##### col

+ `(col A c)`

Return column as a vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L959">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols"></span>
```


##### cols

+ `(cols A)`

Return matrix columns


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L912">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols-&gt;RealMatrix"></span>
```


##### cols->RealMatrix

+ `(cols->RealMatrix cols)`

Return Apache Commons Math Array2DRowMatrix from sequence of columns


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L785">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols-&gt;mat"></span>
```


##### cols->mat

+ `(cols->mat real-matrix-cols)`
+ `(cols->mat [a00 a10] [a01 a11])`
+ `(cols->mat [a00 a10 a20] [a01 a11 a21] [a02 a12 a22])`
+ `(cols->mat [a00 a10 a20 a30] [a01 a11 a21 a31] [a02 a12 a22 a32] [a03 a13 a23 a33])`

Create nxn matrix from nd vectors (columns).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L814">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols-&gt;mat2x2"></span>
```


##### cols->mat2x2

+ `(cols->mat2x2 [a00 a10] [a01 a11])`

Create 2x2 matrix from 2d vectors (columns).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L712">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols-&gt;mat3x3"></span>
```


##### cols->mat3x3

+ `(cols->mat3x3 [a00 a10 a20] [a01 a11 a21] [a02 a12 a22])`

Create 3x3 matrix from 3d vectors (columns).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L739">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cols-&gt;mat4x4"></span>
```


##### cols->mat4x4

+ `(cols->mat4x4 [a00 a10 a20 a30] [a01 a11 a21 a31] [a02 a12 a22 a32] [a03 a13 a23 a33])`

Create 4x4 matrix from 4d vectors (columns).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L770">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-condition"></span>
```


##### condition

+ `(condition A)`
+ `(condition A norm-type)`

Condition number calculated for L2 norm by default (see [norm](#LOS-norm) for other norm types).

   Cond(A) = norm(A) * norm(inv(A))


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1172">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cos"></span>
```


##### cos

+ `(cos vector)`

Apply cos to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cosh"></span>
```


##### cosh

+ `(cosh vector)`

Apply cosh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-cot"></span>
```


##### cot

+ `(cot vector)`

Apply cot to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-coth"></span>
```


##### coth

+ `(coth vector)`

Apply coth to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-csc"></span>
```


##### csc

+ `(csc vector)`

Apply csc to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-csch"></span>
```


##### csch

+ `(csch vector)`

Apply csch to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-degrees"></span>
```


##### degrees

+ `(degrees vector)`

Apply degrees to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-det"></span>
```


##### det

+ `(det A)`

Return determinant of the matrix.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L981">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-diag"></span>
```


##### diag

+ `(diag A)`

Return diagonal of the matrix as a vector.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L977">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-diagonal"></span>
```


##### diagonal

+ `(diagonal v)`
+ `(diagonal a11 a22)`
+ `(diagonal a11 a22 a33)`
+ `(diagonal a11 a22 a33 a44)`

Create diagonal matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L857">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-eigenvalues"></span>
```


##### eigenvalues

+ `(eigenvalues A)`

Return complex eigenvalues for given matrix as a sequence


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1053">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-eigenvalues-matrix"></span>
```


##### eigenvalues-matrix

+ `(eigenvalues-matrix A)`

Return eigenvalues for given matrix as a diagonal or block diagonal matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1069">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-eigenvectors"></span>
```


##### eigenvectors

+ `(eigenvectors A)`
+ `(eigenvectors A normalize?)`

Return eigenvectors as a matrix (columns). Vectors can be normalized.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1135">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-emulm"></span>
```


##### emulm

+ `(emulm A B)`

Multiply two matrices element-wise, Hadamard product, C=AoB


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1023">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-entry"></span>
```


##### entry

+ `(entry A row col)`

Get entry at given row and column


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L903">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-exp"></span>
```


##### exp

+ `(exp vector)`

Apply exp to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-expm1"></span>
```


##### expm1

+ `(expm1 vector)`

Apply expm1 to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-eye"></span>
```


##### eye

+ `(eye size)`

Identity matrix for given size


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L830">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-floor"></span>
```


##### floor

+ `(floor vector)`

Apply floor to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-fmap"></span>
```


##### fmap

+ `(fmap A f)`

Apply a function `f` to each matrix element.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L908">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-frac"></span>
```


##### frac

+ `(frac vector)`

Apply frac to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-inverse"></span>
```


##### inverse

+ `(inverse m)`

Matrix inversion.

  Returns `nil` if inversion doesn't exist.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L971">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ln"></span>
```


##### ln

+ `(ln vector)`

Apply ln to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log"></span>
```


##### log

+ `(log vector)`

Apply log to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log10"></span>
```


##### log10

+ `(log10 vector)`

Apply log10 to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1mexp"></span>
```


##### log1mexp

+ `(log1mexp vector)`

Apply log1mexp to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1p"></span>
```


##### log1p

+ `(log1p vector)`

Apply log1p to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1pexp"></span>
```


##### log1pexp

+ `(log1pexp vector)`

Apply log1pexp to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1pmx"></span>
```


##### log1pmx

+ `(log1pmx vector)`

Apply log1pmx to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log1psq"></span>
```


##### log1psq

+ `(log1psq vector)`

Apply log1psq to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-log2"></span>
```


##### log2

+ `(log2 vector)`

Apply log2 to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logexpm1"></span>
```


##### logexpm1

+ `(logexpm1 vector)`

Apply logexpm1 to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logit"></span>
```


##### logit

+ `(logit vector)`

Apply logit to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-logmxp1"></span>
```


##### logmxp1

+ `(logmxp1 vector)`

Apply logmxp1 to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat"></span>
```


##### mat

+ `(mat real-matrix-rows)`
+ `(mat a00 a01 a10 a11)`
+ `(mat a00 a01 a02 a10 a11 a12 a20 a21 a22)`
+ `(mat a00 a01 a02 a03 a10 a11 a12 a13 a20 a21 a22 a23 a30 a31 a32 a33)`

Create mat2x2, mat3x3 or mat4x4 or RealMatrix from rows


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L790">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;RealMatrix"></span>
```


##### mat->RealMatrix

+ `(mat->RealMatrix A)`

Return Apache Commons Math Array2DRowMatrix from a 2x2, 3x3 or 4x4 matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L940">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;array"></span>
```


##### mat->array

+ `(mat->array A)`

Return flat double array of entries (row order)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L932">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;array2d"></span>
```


##### mat->array2d

+ `(mat->array2d A)`

Return doubles of doubles


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L924">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;float-array"></span>
```


##### mat->float-array

+ `(mat->float-array A)`

Return flat float array of entries (row order)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L936">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;float-array2d"></span>
```


##### mat->float-array2d

+ `(mat->float-array2d A)`

Return doubles of doubles


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L928">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat-&gt;seq"></span>
```


##### mat->seq

+ `(mat->seq A)`

Return flat sequence of entries (row order)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L920">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat2x2"></span>
```


##### mat2x2

+ `(mat2x2 v)`
+ `(mat2x2 d1 d2)`
+ `(mat2x2 a00 a01 a10 a11)`

Create 2x2 matrix.

  Arity:

  * 1 - fills matrix with given value
  * 2 - creates diagonal matrix
  * 4 - creates row ordered matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L694">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat3x3"></span>
```


##### mat3x3

+ `(mat3x3 v)`
+ `(mat3x3 d1 d2 d3)`
+ `(mat3x3 a00 a01 a02 a10 a11 a12 a20 a21 a22)`

Create 3x3 matrix.

  Arity:

  * 1 - fills matrix with given value
  * 3 - creates diagonal matrix
  * 9 - creates row ordered matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L718">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mat4x4"></span>
```


##### mat4x4

+ `(mat4x4 v)`
+ `(mat4x4 d1 d2 d3 d4)`
+ `(mat4x4 a00 a01 a02 a03 a10 a11 a12 a13 a20 a21 a22 a23 a30 a31 a32 a33)`

Create 4x4 matrix.

  Arity:

  * 1 - fills matrix with given value
  * 4 - creates diagonal matrix
  * 16 - creates row ordered matrix


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L746">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mulm"></span>
```


##### mulm

+ `(mulm A B)`
+ `(mulm A transposeA? B transposeB?)`

Multiply two matrices, C=AxB.

  Optionally you can request transposition of matrices.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1003">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mulmt"></span>
```


##### mulmt

+ `(mulmt A B)`

Multiply with transposed matrix, C=AxB^T


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1011">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-muls"></span>
```


##### muls

+ `(muls A s)`

Multply matrix by a scalar, C=sA


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1031">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-mulv"></span>
```


##### mulv

+ `(mulv A v)`

Multply matrix by vector, x=Av


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1027">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-ncol"></span>
```


##### ncol

+ `(ncol A)`

Return number of rows


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L951">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-negate"></span>
```


##### negate

+ `(negate A)`

Negate all matrix elements, C=-A


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L999">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-norm"></span>
```


##### norm

+ `(norm A)`
+ `(norm A norm-type)`

Calculate norm of the matrix for given type, default: 1 (maximum absolute column sum).

  All norm types are:
  * 1 - maximum absolute column sum
  * :inf -  maximum absolute row sum
  * 2 - spectral norm, maximum singular value
  * :max - maximum absolute value
  * :frobenius - Frobenius norm
  * [p,q] - generalized L_pq norm, [2,2] - Frobenius norm, [p,p] - entrywise p-norm
  * [p] - Shatten p-norm, [1] - nuclear/trace norm


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1149">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-normalize"></span>
```


##### normalize

+ `(normalize A)`
+ `(normalize A rows?)`

Normalize columns (or rows)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1079">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-nrow"></span>
```


##### nrow

+ `(nrow A)`

Return number of rows


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L947">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-outer"></span>
```


##### outer

+ `(outer v1 v2)`

Outer project for two vectors.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L875">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-radians"></span>
```


##### radians

+ `(radians vector)`

Apply radians to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rint"></span>
```


##### rint

+ `(rint vector)`

Apply rint to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-2d"></span>
```


##### rotation-matrix-2d

+ `(rotation-matrix-2d theta)`

Create rotation matrix for a plane


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1181">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-3d"></span>
```


##### rotation-matrix-3d

+ `(rotation-matrix-3d [x y z])`
+ `(rotation-matrix-3d x y z)`

Create rotation matrix for a 3d space. TaitBryan angles z-y-x


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1188">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-3d-x"></span>
```


##### rotation-matrix-3d-x

+ `(rotation-matrix-3d-x a)`

Create rotation matrix for a 3d space, x-axis, right hand rule.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1204">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-3d-y"></span>
```


##### rotation-matrix-3d-y

+ `(rotation-matrix-3d-y a)`

Create rotation matrix for a 3d space, y-axis, right hand rule.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1213">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-3d-z"></span>
```


##### rotation-matrix-3d-z

+ `(rotation-matrix-3d-z a)`

Create rotation matrix for a 3d space, z-axis, right hand rule.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1222">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rotation-matrix-axis-3d"></span>
```


##### rotation-matrix-axis-3d

+ `(rotation-matrix-axis-3d angle axis)`

Create 3d rotation matrix for axis ratation.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1231">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-round"></span>
```


##### round

+ `(round vector)`

Apply round to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-row"></span>
```


##### row

+ `(row A r)`

Return row as a vector


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L955">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows"></span>
```


##### rows

+ `(rows A)`

Return matrix rows


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L916">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows-&gt;RealMatrix"></span>
```


##### rows->RealMatrix

+ `(rows->RealMatrix rows)`

Return Apache Commons Math Array2DRowMatrix from sequence of rows


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L778">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows-&gt;mat"></span>
```


##### rows->mat

+ `(rows->mat real-matrix-rows)`
+ `(rows->mat [a00 a01] [a10 a11])`
+ `(rows->mat [a00 a01 a02] [a10 a11 a12] [a20 a21 a22])`
+ `(rows->mat [a00 a01 a02 a03] [a10 a11 a12 a13] [a20 a21 a22 a23] [a30 a31 a32 a33])`

Create nxn matrix from nd vectors (rows).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L798">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows-&gt;mat2x2"></span>
```


##### rows->mat2x2

+ `(rows->mat2x2 [a00 a01] [a10 a11])`

Create 2x2 matrix from 2d vectors (rows).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L706">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows-&gt;mat3x3"></span>
```


##### rows->mat3x3

+ `(rows->mat3x3 [a00 a01 a02] [a10 a11 a12] [a20 a21 a22])`

Create 3x3 matrix from 3d vectors (rows).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L732">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-rows-&gt;mat4x4"></span>
```


##### rows->mat4x4

+ `(rows->mat4x4 [a00 a01 a02 a03] [a10 a11 a12 a13] [a20 a21 a22 a23] [a30 a31 a32 a33])`

Create 4x4 matrix from 4d vectors (rows).


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L762">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-safe-sqrt"></span>
```


##### safe-sqrt

+ `(safe-sqrt vector)`

Apply safe-sqrt to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-scale-cols"></span>
```


##### scale-cols

+ `(scale-cols A)`
+ `(scale-cols A scale)`

Shift columns by a value (default: sqrt(sum(x^2)/(n-1))) or a result of the function


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1125">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-scale-rows"></span>
```


##### scale-rows

+ `(scale-rows A)`
+ `(scale-rows A scale)`

Shift rows by a value (default: sqrt(sum(x^2)/(n-1))) or a result of the function


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1115">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sec"></span>
```


##### sec

+ `(sec vector)`

Apply sec to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sech"></span>
```


##### sech

+ `(sech vector)`

Apply sech to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sfrac"></span>
```


##### sfrac

+ `(sfrac vector)`

Apply sfrac to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sgn"></span>
```


##### sgn

+ `(sgn vector)`

Apply sgn to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-shift-cols"></span>
```


##### shift-cols

+ `(shift-cols A)`
+ `(shift-cols A shift)`

Shift columns by a value or a result of the function (mean by default)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1103">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-shift-rows"></span>
```


##### shift-rows

+ `(shift-rows A)`
+ `(shift-rows A shift)`

Shift rows by a value or a result of the function (mean by default)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1093">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sigmoid"></span>
```


##### sigmoid

+ `(sigmoid vector)`

Apply sigmoid to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-signum"></span>
```


##### signum

+ `(signum vector)`

Apply signum to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sin"></span>
```


##### sin

+ `(sin vector)`

Apply sin to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sinc"></span>
```


##### sinc

+ `(sinc vector)`

Apply sinc to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-singular-values"></span>
```


##### singular-values

+ `(singular-values A)`

Returun singular values of the matrix as sqrt of eigenvalues of A^T * A matrix.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1061">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sinh"></span>
```


##### sinh

+ `(sinh vector)`

Apply sinh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-solve"></span>
```


##### solve

+ `(solve A b)`

Solve linear equation Ax=b


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L869">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sq"></span>
```


##### sq

+ `(sq vector)`

Apply sq to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sqrt"></span>
```


##### sqrt

+ `(sqrt vector)`

Apply sqrt to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-sub"></span>
```


##### sub

+ `(sub A)`
+ `(sub A B)`

Subract matrices, C=A-B.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L994">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-symmetric?"></span>
```


##### symmetric?

+ `(symmetric? A)`

Check if matrix is symmetric


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L963">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tan"></span>
```


##### tan

+ `(tan vector)`

Apply tan to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tanh"></span>
```


##### tanh

+ `(tanh vector)`

Apply tanh to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tmulm"></span>
```


##### tmulm

+ `(tmulm A B)`

Transpose and multiply, C=A^TxB


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1015">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-tmulmt"></span>
```


##### tmulmt

+ `(tmulmt A B)`

Transpose both and multiply, C=A^TxB^T


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1019">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-trace"></span>
```


##### trace

+ `(trace A)`

Return trace of the matrix (sum of diagonal elements)


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1049">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-transpose"></span>
```


##### transpose

+ `(transpose A)`

Transpose matrix, C=A^T


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L967">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-trunc"></span>
```


##### trunc

+ `(trunc vector)`

Apply trunc to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-vtmul"></span>
```


##### vtmul

+ `(vtmul A v)`

Multiply transposed vector by matrix, C=v^T A


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1035">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-xlogx"></span>
```


##### xlogx

+ `(xlogx vector)`

Apply xlogx to matrix elements.


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L1256">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<span id="#LOS-zero"></span>
```


##### zero

+ `(zero size)`

Zero matrix for given size


```{=html}
<div style="text-align: right"><small><a href="https://github.com/generateme/fastmath/tree/3.x/src/fastmath/matrix.clj#L846">source</a></small><hr style="margin: 0" /></div>
```



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: <a href="https://github.com/generateme/fastmath//blob/master/clay/vector_matrix.clj">clay/vector_matrix.clj</a></small></small></pre></div>
```
