"""One-off generator of independent reference values for the Meixner-Pollaczek polynomials of
`fastmath.polynomials`: `eval-meixner-pollaczek-P`, `meixner-pollaczek-P-ratio` and
`meixner-pollaczek-P`.

Produces `test/resources/polynomials/meixner_pollaczek_reference.edn`. The values are computed with `mpmath`
at 60 digits, with the exact binary values of the parameters `lambda`, `phi` and of the argument `x`
(`cos phi` and `sin phi` are those of the exact double `phi`), then rounded once to a double.

For `lambda > 0` the polynomial comes from the hypergeometric definition, a route independent of the
recurrence the library uses:

  P_n^(lambda)(x; phi) = (2 lambda)_n / n! * exp(i n phi) * 2F1(-n, lambda + i x; 2 lambda; 1 - exp(-2 i phi))

and the generator asserts that it equals the three term recurrence

  (n+1) P_(n+1) = 2 [x sin(phi) + (n + lambda) cos(phi)] P_n - (n + 2 lambda - 1) P_(n-1),  P_0 = 1,

which is then used for the other values of `lambda` (zero and negative, where `2 lambda` can be a
non-positive integer and the hypergeometric form is singular). The first derivative in `x`, from the
differentiated recurrence, is stored too. A row is left out when the value or the derivative is not a finite
double.

Layout: `[{:lambda l :phi p :source :hypergeometric|:recurrence :grid [[n x value derivative] ...]} ...]`.

Run with (from repo root, using the `uv`-managed Python env mentioned in AGENTS.md):
    cd /home/ts/penv && uv run python \
        /home/ts/clojure/fastmath/utils/fastmath/dev/generate_meixner_pollaczek_reference.py
"""
import math
import mpmath as mp

mp.mp.dps = 60
OUT = "/home/ts/clojure/fastmath/test/resources/polynomials/meixner_pollaczek_reference.edn"
DBL_MAX = 1.7976931348623157e308


def recurrence(n, lam, phi, x):
    """P_n and dP_n/dx by the three term recurrence, in mp arithmetic."""
    lam, phi, x = mp.mpf(lam), mp.mpf(phi), mp.mpf(x)
    c, s = mp.cos(phi), mp.sin(phi)
    p0, d0 = mp.mpf(1), mp.mpf(0)
    if n == 0:
        return p0, d0
    p1 = 2 * (x * s + lam * c)
    d1 = 2 * s
    for k in range(1, n):
        p2 = (2 * (x * s + (k + lam) * c) * p1 - (k + 2 * lam - 1) * p0) / (k + 1)
        d2 = (2 * (s * p1 + (x * s + (k + lam) * c) * d1) - (k + 2 * lam - 1) * d0) / (k + 1)
        p0, d0, p1, d1 = p1, d1, p2, d2
    return p1, d1


def hypergeometric(n, lam, phi, x):
    lam, phi, x = mp.mpf(lam), mp.mpf(phi), mp.mpf(x)
    z = 1 - mp.exp(-2j * phi)
    value = mp.rf(2 * lam, n) / mp.factorial(n) * mp.exp(1j * n * phi) * mp.hyp2f1(-n, lam + 1j * x, 2 * lam, z)
    return value


def to_double(v):
    v = float(v)
    return v if abs(v) <= DBL_MAX else None


def fmt(v):
    return repr(float(v))


LAMBDAS = [0.25, 0.5, 1.0, 2.5, 7.0, 0.0, -0.5, -1.5]
PHIS = [0.1, 0.5, math.pi / 4, math.pi / 2, 2.0, 3.0, math.pi, -1.0, 7.0, 0.0]
XS = sorted(set([0.0, 1e-9, 0.1, 0.5, 1.0, 2.0, 3.5, 7.0, 10.0, 30.0, 100.0] + [-v for v in [1e-9, 0.1, 0.5, 1.0, 2.0, 3.5, 7.0, 10.0, 30.0, 100.0]]))
DEGREES = [0, 1, 2, 3, 4, 5, 6, 8, 10, 20, 30, 50]

# the recurrence agrees with the hypergeometric definition (lambda > 0)
worst = 0
for lam in (0.25, 0.5, 1.0, 2.5):
    for phi in (0.1, math.pi / 2, 3.0):
        for n in (1, 2, 3, 5, 8):
            for x in (-3.5, 0.0, 0.5, 7.0):
                h = hypergeometric(n, lam, phi, x)
                r, _ = recurrence(n, lam, phi, x)
                assert abs(h.imag) < mp.mpf(10) ** -40 * max(1, abs(r)), ("imaginary part", lam, phi, n, x, h)
                worst = max(worst, abs(h.real - r) / max(1, abs(r)))
assert worst < mp.mpf(10) ** -40, worst
print("recurrence vs hypergeometric: largest relative difference %s" % mp.nstr(worst, 3))

blocks = []
rows_total = 0
for lam in LAMBDAS:
    for phi in PHIS:
        rows = []
        for n in DEGREES:
            for x in XS:
                v, d = recurrence(n, lam, phi, x)
                dv, dd = to_double(v), to_double(d)
                if dv is None or dd is None:
                    continue
                rows.append("[%d %s %s %s]" % (n, fmt(x), fmt(dv), fmt(dd)))
        rows_total += len(rows)
        blocks.append("  {:lambda %s :phi %s :source %s\n   :grid [%s]}" % (
            fmt(lam), fmt(phi), ":hypergeometric" if lam > 0 else ":recurrence", "\n    ".join(rows)))

with open(OUT, "w") as f:
    f.write(";; Generated by utils/fastmath/dev/generate_meixner_pollaczek_reference.py (mpmath, 60 digits)\n")
    f.write("[\n" + "\n".join(blocks) + "\n]\n")

print("parameter pairs:", len(blocks), "rows:", rows_total)
print("wrote", OUT)
