"""One-off generator of independent reference values for the scalar polynomial
evaluators of `fastmath.polynomials` (`evalpoly`, `mevalpoly`, `makepoly`,
`evalpoly-complex`, `mevalpoly-complex`, `makepoly-complex`,
`evalpoly-scalar-complex`, `mevalpoly-scalar-complex`,
`makepoly-scalar-complex`).

Produces `test/resources/polynomials/evalpoly_reference.edn`, computed with
`mpmath` at 50 digits from the exact double coefficients and double arguments
(no rounding is introduced before the final conversion to double):
  - `:real`            real coefficients, real `x`
  - `:complex`         complex coefficients (`[re im]` pairs), complex `z`
  - `:scalar-complex`  real coefficients, complex `z`

Each block is `{:polys [...] :x|:z [...] :ref [[...] ...]}`; `:ref` is a matrix,
one row per polynomial and one column per argument. Coefficients are in
ascending order (`c0 + c1*x + c2*x^2 + ...`), as in `fastmath.polynomials`.

Polynomials have 1..11 coefficients (degree 0..10), random values in [-5, 5]
with some exact zeros, plus fixed hand-chosen polynomials (all-zero, single
coefficient, trailing zero coefficient, leading zero coefficient). Arguments
include 0, +-1, small, large and values close to the sign changes of the
polynomials, so the roundoff behaviour is exercised away from the benign
region. The random sequence is seeded, so the output is reproducible.

Run with (from repo root, using the `uv`-managed Python env mentioned in
AGENTS.md):
    cd /home/ts/penv && uv run python \
        /home/ts/clojure/fastmath/utils/fastmath/dev/generate_polynomials_reference.py
"""
import random

import mpmath as mp

mp.mp.dps = 50

OUT = "/home/ts/clojure/fastmath/test/resources/polynomials/evalpoly_reference.edn"

random.seed(20261008)

REAL_X = [-1.0e3, -10.0, -3.0, -1.5, -1.0, -0.7, -0.1, -1.0e-8, 0.0, 1.0e-8,
          0.1, 0.5, 1.0, 1.0000001, 1.5, 2.0, 10.0, 1.0e3]
COMPLEX_Z = [(0.0, 0.0), (1.0, 0.0), (-1.0, 0.0), (0.0, 1.0), (0.0, -1.0),
             (1.0, 1.0), (-1.5, 2.0), (0.3, -0.7), (1.0e-8, 1.0e-8),
             (-0.5, -0.25), (2.0, 3.0), (-10.0, 0.5), (0.0, 100.0),
             (1.0e3, -1.0e3)]


def random_coeff():
    return 0.0 if random.random() < 0.15 else round(random.uniform(-5.0, 5.0), 12)


def random_real_poly(n):
    return [random_coeff() for _ in range(n)]


def random_complex_poly(n):
    return [[random_coeff(), random_coeff()] for _ in range(n)]


FIXED_REAL = [
    [0.0],
    [0.0, 0.0],
    [0.0, 0.0, 0.0],
    [1.0],
    [-2.5],
    [1.0, 2.0],
    [0.0, 1.0],
    [1.0, 0.0],
    [0.0, 0.0, 1.0],
    [1.0, 2.0, 3.0, 0.0],
    [0.0, 2.0, 3.0],
    [1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0],
]

FIXED_COMPLEX = [
    [[0.0, 0.0]],
    [[1.0, 2.0]],
    [[0.0, 0.0], [0.0, 0.0]],
    [[1.0, 2.0], [0.0, 1.0]],
    [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]],
    [[1.0, 0.0], [0.0, 0.0], [0.0, 0.0], [1.0, 1.0]],
]


def mp_horner_real(cs, x):
    acc = mp.mpf(0)
    for c in reversed(cs):
        acc = acc * mp.mpf(x) + mp.mpf(c)
    return acc


def mp_horner_complex(cs, z):
    zz = mp.mpc(z[0], z[1])
    acc = mp.mpc(0)
    for c in reversed(cs):
        acc = acc * zz + mp.mpc(c[0], c[1])
    return acc


def fmt(x):
    return repr(float(x))


def edn_vec(xs):
    return "[" + " ".join(fmt(x) for x in xs) + "]"


def edn_vecs(xss):
    return "[" + " ".join(edn_vec(xs) for xs in xss) + "]"


def edn_cvec(zs):
    return "[" + " ".join(edn_vec(z) for z in zs) + "]"


def edn_cvecs(zss):
    return "[" + " ".join(edn_cvec(zs) for zs in zss) + "]"


real_polys = FIXED_REAL + [random_real_poly(n) for n in range(1, 12) for _ in range(3)]
complex_polys = FIXED_COMPLEX + [random_complex_poly(n) for n in range(1, 12) for _ in range(2)]

real_ref = [[mp_horner_real(cs, x) for x in REAL_X] for cs in real_polys]
complex_ref = [[mp_horner_complex(cs, z) for z in COMPLEX_Z] for cs in complex_polys]
scalar_complex_ref = [[mp_horner_complex([[c, 0.0] for c in cs], z) for z in COMPLEX_Z] for cs in real_polys]


def edn_complex_matrix(rows):
    return "[" + " ".join(
        "[" + " ".join("[" + fmt(v.real) + " " + fmt(v.imag) + "]" for v in row) + "]"
        for row in rows) + "]"


def edn_real_matrix(rows):
    return "[" + " ".join(edn_vec(row) for row in rows) + "]"


with open(OUT, "w") as f:
    f.write(";; Generated by utils/fastmath/dev/generate_polynomials_reference.py (mpmath, 50 digits)\n")
    f.write("{:real\n {:polys " + edn_vecs(real_polys) + "\n")
    f.write("  :x " + edn_vec(REAL_X) + "\n")
    f.write("  :ref " + edn_real_matrix(real_ref) + "}\n")
    f.write(" :complex\n {:polys [" + " ".join(edn_cvec(p) for p in complex_polys) + "]\n")
    f.write("  :z " + edn_cvec(COMPLEX_Z) + "\n")
    f.write("  :ref " + edn_complex_matrix(complex_ref) + "}\n")
    f.write(" :scalar-complex\n {:polys " + edn_vecs(real_polys) + "\n")
    f.write("  :z " + edn_cvec(COMPLEX_Z) + "\n")
    f.write("  :ref " + edn_complex_matrix(scalar_complex_ref) + "}}\n")

print("real polys:", len(real_polys), "x", len(REAL_X))
print("complex polys:", len(complex_polys), "x", len(COMPLEX_Z))
print("wrote", OUT)
