"""One-off generator of independent reference values for the Chebyshev polynomials of
`fastmath.polynomials`: `eval-chebyshev-T/U/V/W`, `chebyshev-T/U/V/W-ratio`, `chebyshev-T/U/V/W`
(first to fourth kind).

Produces `test/resources/polynomials/chebyshev_reference.edn`. Everything is exact rational
arithmetic (`fractions.Fraction`): the integer coefficients come from the recurrence
`p(n+1) = 2x p(n) - p(n-1)` with `p(0) = 1` and `p(1) = x, 2x, 2x-1, 2x+1` for T, U, V, W, and the
values and the first derivatives are evaluated at the exact binary value of every double argument,
then rounded once to a double (so the reference has no rounding error of its own beyond that).

Blocks:
  - `:coefficients`  `{:T [[...] ...] ...}` coefficients of degree 0..40, ascending order of power
  - `:grid`          `{:T [[n x value derivative] ...] ...}` a dense grid around the places where
                     an evaluation could change branch or lose accuracy: 0, +-1, +-(1 - delta) and
                     +-(1 + delta) for many deltas (down to the neighbouring doubles of 1), the
                     point 1/sqrt(2), moderate and large |x|; degrees 0..500
  - `:large`         `{:T [[n x value] ...] ...}` large arguments with a finite value, where an
                     intermediate quantity of an implementation could overflow before the result does

Entries whose value or derivative is not representable as a double are left out.

Run with (from repo root, using the `uv`-managed Python env mentioned in AGENTS.md):
    cd /home/ts/penv && uv run python \
        /home/ts/clojure/fastmath/utils/fastmath/dev/generate_chebyshev_reference.py
"""
import math
from fractions import Fraction

OUT = "/home/ts/clojure/fastmath/test/resources/polynomials/chebyshev_reference.edn"
DBL_MAX = 1.7976931348623157e308

KINDS = {"T": [0, 1], "U": [0, 2], "V": [-1, 2], "W": [1, 2]}


def coefficients(kind, n):
    p_prev, p = [1], KINDS[kind]
    if n == 0:
        return [1]
    for _ in range(n - 1):
        nxt = [0] + [2 * c for c in p]
        for i, c in enumerate(p_prev):
            nxt[i] -= c
        p_prev, p = p, nxt
    return p


def horner(cs, x):
    acc = Fraction(0)
    for c in reversed(cs):
        acc = acc * x + c
    return acc


def derivative(cs):
    return [i * c for i, c in enumerate(cs)][1:] or [0]


def to_double(q):
    q = Fraction(q)
    try:
        v = float(q)
    except OverflowError:
        return None
    return v if abs(v) <= DBL_MAX else None


def fmt(v):
    return repr(float(v))


def x_grid():
    xs = {0.0, 1e-9, 0.1, 0.5, 0.7071067811865476, 0.9, 1.5, 2.0, 10.0, 100.0, 1e4, 1e8, 1e15}
    for k in range(1, 17):
        xs.add(1.0 - 10.0 ** -k)
    for k in range(1, 16):
        xs.add(1.0 + 10.0 ** -k)
    for k in range(3, 11):
        for c in (1.0, 2.0, 5.0):
            xs.add(1.0 - c * 10.0 ** -k)
    up, down = 1.0, 1.0
    for _ in range(4):
        up, down = math.nextafter(up, 2.0), math.nextafter(down, 0.0)
        xs.add(up)
        xs.add(down)
    xs.add(1.0)
    return sorted(xs | {-x for x in xs})


DEGREES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 15, 20, 30, 50, 100, 200, 500]
XS = x_grid()

LARGE_X = [1e20, 1e50, 1e60, 1e75, 1e100, 1e150, 1e200, 1e300]

coeff_cache = {(k, n): coefficients(k, n) for k in KINDS for n in range(0, 501) if n <= 40 or n in DEGREES}

with open(OUT, "w") as f:
    f.write(";; Generated by utils/fastmath/dev/generate_chebyshev_reference.py (exact rational arithmetic)\n")
    f.write("{:coefficients {\n")
    for k in KINDS:
        f.write("  :%s [%s]\n" % (k, " ".join("[" + " ".join(str(c) for c in coeff_cache[(k, n)]) + "]" for n in range(0, 41))))
    f.write(" }\n :grid {\n")
    counts = {}
    for k in KINDS:
        rows = []
        for n in DEGREES:
            cs = coeff_cache[(k, n)]
            ds = derivative(cs)
            for x in XS:
                xf = Fraction(x)
                v, d = to_double(horner(cs, xf)), to_double(horner(ds, xf))
                if v is None or d is None:
                    continue
                rows.append("[%d %s %s %s]" % (n, fmt(x), fmt(v), fmt(d)))
        counts[k] = len(rows)
        f.write("  :%s [%s]\n" % (k, "\n    ".join(rows)))
    f.write(" }\n :large {\n")
    for k in KINDS:
        rows = []
        for x in LARGE_X:
            xf = Fraction(x)
            for n in range(0, 40):
                v = to_double(horner(coefficients(k, n), xf))
                if v is None:
                    break
                rows.append("[%d %s %s]" % (n, fmt(x), fmt(v)))
        f.write("  :%s [%s]\n" % (k, "\n    ".join(rows)))
    f.write(" }}\n")

print("x points:", len(XS), "degrees:", len(DEGREES), "grid rows:", counts)
print("wrote", OUT)
