(ns fastmath.ml.regression-test
  (:require [fastmath.ml.regression :as sut]
            [clojure.test :as t]
            [fastmath.core :as m]
            [clojure.pprint]
            [fastmath.vector :as v]
            [fastmath.matrix :as mat]
            [fastmath.ml.regression.contrast :as contrast]
            [clojure.edn :as edn]
            [clojure.java.io :as io]))

;; §2.2: shared, memoized EDN reference loader -- all R-fitted reference
;; values live in `test/resources/regression/*_reference.edn` (generated by
;; `fastmath.dev.regression-ref-gen`), so no live R session is needed to run
;; this test suite.

(def ^:private load-ref
  "Load and parse one `test/resources/regression/<name>_reference.edn` file.
  Memoized: each file is read and parsed at most once per test run,
  regardless of how many deftests/calls reference it."
  (memoize
   (fn [name]
     (-> (str "regression/" name "_reference.edn")
         io/resource
         slurp
         edn/read-string))))

;; §2.3: `col` is a raw categorical column (a seq of keywords); `values` are
;; the non-reference levels to build 0/1 columns for, matching the original
;; tablecloth `one-hot`'s calling convention. The reference level is
;; whichever level of `col` is not in `values`. Delegates to `contrast/dummy`;
;; duplicated (not shared) with the generator's own copy, per §4.

(defn- one-hot
  [col values]
  (let [levels (distinct col)
        reference (first (remove (set values) levels))
        coding (contrast/dummy (cons reference values))
        columns (apply map vector (map (:mapping coding) col))]
    (zipmap values columns)))

;; §2.3 extension: `col1`/`col2` are raw categorical columns. Reproduces the
;; original tablecloth `mult-columns`' exact column order and default
;; (first-appearance, sort1?/sort2?=false) reference-level convention.

(defn- mult-columns
  [col1 col2]
  (let [cs1 (vec (rest (distinct col1)))
        cs2 (vec (rest (distinct col2)))
        oh1 (one-hot col1 cs1)
        oh2 (one-hot col2 cs2)
        onehot1-cols (map oh1 cs1)
        onehot2-cols (map oh2 cs2)
        interactions (for [c2 cs2 c1 cs1] (mapv * (oh1 c1) (oh2 c2)))]
    {:cs1 cs1 :cs2 cs2 :xss (apply map vector (concat onehot1-cols onehot2-cols interactions))}))

;; §2.4 (superseded): `add-poly` (a pure-fastmath port wrapping
;; `v/orthonormal-polynomials`) has been replaced at both its call sites
;; (`deposit-data`, `danishlc-data`) by `sut/polynomial-transformer`, used via
;; the model's own `:transformer` option -- unlike `add-poly`, it is a genuine
;; fitted closure that can be evaluated at *new* x values, enabling a
;; newdata-predict check for both poly-encoded deftests. See the topic note
;; "Fastmath Regression Test R and Tablecloth Removal" (Continuation).

;; §3.1: named comparators, fine-grained -- each performs one `t/is` per field.
;; Shared between LM and GLM (identical shape on both sides):

(defn- check-coefficients
  "3.1.1. `coefs` = (:coefficients lm-or-glm), a seq of per-coefficient maps.
  `ref` = {:estimate [...] :stderr [...] :t-value|:z-value [...] :p-value [...]}.
  Reads whichever of :t-value/:z-value `ref` carries."
  [coefs ref]
  (t/is (v/delta-eq (map :estimate coefs) (:estimate ref)))
  (t/is (v/delta-eq (map :stderr coefs) (:stderr ref)))
  (let [stat-key (if (contains? ref :t-value) :t-value :z-value)]
    (t/is (v/delta-eq (map stat-key coefs) (stat-key ref))))
  (t/is (v/delta-eq (map :p-value coefs) (:p-value ref))))

(defn- check-xtxinv
  "3.1.2."
  [xtxinv ref]
  (t/is (v/delta-eq (mat/mat->seq xtxinv) ref)))

(defn- check-correlation
  "3.1.3. `correlation` = (:correlation analysis), a matrix; `ref` is flat."
  [correlation ref]
  (t/is (v/delta-eq (flatten correlation) ref)))

(defn- check-leverage
  "3.1.4."
  [leverage ref]
  (t/is (v/delta-eq (:hat leverage) (:hat ref)))
  (t/is (v/delta-eq (:sigmas leverage) (:sigmas ref)))
  (t/is (v/delta-eq (flatten (:coefficients leverage)) (:coefficients ref))))

(defn- check-influence
  "3.1.5. Optional `cooks-tol` (GLM uses 1e-5, LM uses the default)."
  ([influence ref] (check-influence influence ref nil))
  ([influence ref cooks-tol]
   (t/is (if cooks-tol
           (v/delta-eq (:cooks-distance influence) (:cooks-distance ref) cooks-tol)
           (v/delta-eq (:cooks-distance influence) (:cooks-distance ref))))
   (t/is (v/delta-eq (:dffits influence) (:dffits ref)))
   (t/is (v/delta-eq (:covratio influence) (:covratio ref)))
   (t/is (v/delta-eq (flatten (:dfbetas influence)) (:dfbetas ref)))))

(defn- check-df
  "3.1.6. Key-presence tolerant: checks whichever keys `ref` carries
  (LM: :residual/:model, GLM: :residual/:null)."
  [df ref]
  (doseq [k (keys ref)]
    (t/is (== (get df k) (get ref k)))))

(defn- check-ll
  "3.1.7. Key-presence tolerant (LM carries extra :aic-rss/:bic-rss)."
  [ll ref]
  (doseq [k (keys ref)]
    (t/is (m/delta-eq (get ll k) (get ref k)))))

;; LM-specific:

(defn- check-residuals-lm
  "3.1.8."
  [residuals ref]
  (t/is (v/delta-eq (:raw residuals) (:raw ref)))
  (t/is (v/delta-eq (:weighted residuals) (:weighted ref))))

(defn- check-fit-lm
  "3.1.9."
  [lm ref]
  (t/is (v/delta-eq (:fitted lm) (:fitted ref)))
  (t/is (m/delta-eq (:sigma lm) (:sigma ref)))
  (t/is (m/delta-eq (:sigma2 lm) (:sigma2 ref)))
  (t/is (m/delta-eq (:r-squared lm) (:r-squared ref)))
  (t/is (m/delta-eq (:adjusted-r-squared lm) (:adjusted-r-squared ref)))
  (t/is (m/delta-eq (:f-statistic lm) (:f-statistic ref))))

(defn- check-normality
  "3.1.10."
  [normality ref]
  (t/is (m/delta-eq (:skewness normality) (:skewness ref)))
  (t/is (m/delta-eq (:kurtosis normality) (:kurtosis ref)))
  (t/is (m/delta-eq (get-in normality [:durbin-watson :raw]) (:durbin-watson ref))))

(defn- check-analysis-residuals-lm
  "3.1.11."
  [residuals ref]
  (t/is (v/delta-eq (:standardized residuals) (:standardized ref)))
  (t/is (v/delta-eq (:studentized residuals) (:studentized ref))))

;; New-data prediction (fit/stderr/confidence-interval), shared by LM and GLM.
;; `model` is a fitted `LMData`/`GLMData` (implements `IFn`); `newdata-xss` is
;; a seq of points ready to pass straight to `model`/`sut/predict` as-is (i.e.
;; already offset-prepended, matching `with-offset`'s convention, when the
;; model was fit with an offset -- `predict`'s own `:transformer` application
;; happens internally, after offset extraction). `ref` = {:fit [...] :stderr
;; [...] :confidence-interval [[lo hi] ...]}, generated by
;; `fastmath.dev.regression-ref-gen`'s `predict-lm-oracle`/`predict-glm-oracle`.
(defn- check-predict
  [model newdata-xss ref]
  (let [preds (map #(model % true) newdata-xss)]
    (t/is (v/delta-eq (map :fit preds) (:fit ref)))
    (t/is (v/delta-eq (map :stderr preds) (:stderr ref)))
    (t/is (v/delta-eq (mapcat :confidence-interval preds) (flatten (:confidence-interval ref))))))

(def ys [1 2.1 3.2 4 4.9 5.5 10 7 8.1 8.7])
(def nys (v/normalize ys))
(def xss-1 '(-0.5 -1 -2 -3 -4 -5 -6 -7 -8 -9))
(def xss-2 '(1 2 0 2 1 0 1 2 0 2))
(def xss-3 (v/emult xss-1 xss-2))
(def xss (map vector xss-1 xss-2 xss-3))
(def weights [2 1 2 1 2 1 2 1 2 1])
(def offset (range 10))

;; New-data prediction points for basic-lm/dummy-data/gaussian-glm (Tier 1) --
;; two points outside the training x1/x2/offset ranges (x1 in [-9,-0.5], x2 in
;; {0,1,2}, offset in [0,9]), matching `fastmath.dev.regression-ref-gen`'s
;; `basic-new-x1`/`basic-new-x2`/`basic-new-off` exactly. Each point is a
;; [x1 x2 x1*x2] triple, matching `xss`'s own pre-multiplied interaction
;; column (fastmath has no formula support -- the interaction is a literal
;; third column here, same as `xss`/`xss-3` above).
(def new-xss [[-10.0 1.0 -10.0] [-0.3 2.0 -0.6]])
(def new-offset [10.0 11.0])
(defn- with-new-offset
  "Prepend `new-offset` to each of `new-xss`, matching `with-offset`'s
  `[offset x1 x2 ...]` convention."
  [] (map cons new-offset new-xss))

(defn- lm-tests
  "§3.2. `ref-block` is an already-resolved {:model :analysis} map (the
  deftest call site owns loading and, for multi-call files, sub-key
  selection -- decouples this fn from I/O). `options` may carry a test-only
  `:newdata-xss` key (a seq of new-data points, see `check-predict`) -- it is
  passed straight through to `sut/lm` alongside the real fitting options,
  which simply ignores unknown keys, matching `glm-tests`' own
  `:no-analysis?`/`:qres?` convention."
  ([ys xss ref-block] (lm-tests ys xss nil ref-block))
  ([ys xss options ref-block]
   (let [lm (sut/lm ys xss options)
         analysis (sut/analysis lm)]
     (t/is (m/delta-eq (:intercept lm) (get-in ref-block [:model :intercept])))
     (t/is (v/delta-eq (:beta lm) (get-in ref-block [:model :beta])))
     (check-coefficients (:coefficients lm) (get-in ref-block [:model :coefficients]))
     (check-xtxinv (:xtxinv lm) (get-in ref-block [:model :xtxinv]))
     (check-df (:df lm) (get-in ref-block [:model :df]))
     (check-ll (:ll lm) (get-in ref-block [:model :ll]))
     (check-fit-lm lm (:model ref-block))
     (check-residuals-lm (:residuals lm) (get-in ref-block [:model :residuals]))
     (check-correlation (:correlation analysis) (get-in ref-block [:analysis :correlation]))
     (check-normality (:normality analysis) (get-in ref-block [:analysis :normality]))
     (check-analysis-residuals-lm (:residuals analysis) (get-in ref-block [:analysis :residuals]))
     (check-leverage (:leverage analysis) (get-in ref-block [:analysis :leverage]))
     (check-influence (:influence analysis) (get-in ref-block [:analysis :influence]))
     (when-let [predict-ref (get-in ref-block [:extra :predict])]
       (check-predict lm (:newdata-xss options) predict-ref)))))

(t/deftest basic-weights-intercept
  (lm-tests ys xss {:weights weights :newdata-xss new-xss} (load-ref "basic-weights-intercept")))

(t/deftest basic-weights-intercept-transformer
  (lm-tests ys xss {:weights weights :transformer (fn [[a b c]] [(m/exp a) a b c]) :newdata-xss new-xss}
                (load-ref "basic-weights-intercept-transformer")))

(t/deftest basic-weights-intercept-offset
  (lm-tests ys xss {:weights weights :offset offset :newdata-xss (with-new-offset)}
                (load-ref "basic-weights-intercept-offset")))

(t/deftest basic-weights-no-intercept
  (lm-tests ys xss {:weights weights :intercept? false :newdata-xss new-xss} (load-ref "basic-weights-no-intercept")))

(t/deftest basic-weights-no-intercept-offset
  (lm-tests ys xss {:weights weights :intercept? false :offset offset :newdata-xss (with-new-offset)}
                (load-ref "basic-weights-no-intercept-offset")))

(t/deftest basic-no-weights-intercept
  (lm-tests ys xss {:newdata-xss new-xss} (load-ref "basic-no-weights-intercept")))

(t/deftest basic-no-weights-intercept-offset
  (lm-tests ys xss {:offset offset :newdata-xss (with-new-offset)} (load-ref "basic-no-weights-intercept-offset")))

(t/deftest basic-no-weights-no-intercept
  (lm-tests ys xss {:intercept? false :newdata-xss new-xss} (load-ref "basic-no-weights-no-intercept")))

(t/deftest basic-no-weights-no-intercept-offset
  (lm-tests ys xss {:intercept? false :offset offset :newdata-xss (with-new-offset)}
                (load-ref "basic-no-weights-no-intercept-offset")))

;; GLM-specific comparators (§3.1.12-3.1.16, 3.1.19). `check-coefficients`,
;; `check-xtxinv`, `check-correlation`, `check-leverage`, `check-influence`,
;; `check-df`, `check-ll` above are already shared with LM.

(defn- check-residuals-glm
  "3.1.12."
  [residuals ref]
  (t/is (v/delta-eq (:working residuals) (:working ref) 1.0e-5))
  (t/is (v/delta-eq (:deviance residuals) (:deviance ref)))
  (t/is (v/delta-eq (:pearson residuals) (:pearson ref)))
  (t/is (v/delta-eq (:raw residuals) (:raw ref) 1.0e-4)))

(defn- check-fit-glm
  "3.1.13. :deviance :null is deliberately NOT checked here -- the original
  glm-tests only compares it when :compare-deviance-null? is explicitly true
  (default false), so that gate lives at the glm-tests call site instead."
  [glm ref]
  (t/is (v/delta-eq (:fitted glm) (:fitted ref) 1.0e-4))
  (t/is (m/delta-eq (:dispersion glm) (:dispersion ref)))
  (t/is (m/delta-eq (get-in glm [:deviance :residual]) (get-in ref [:deviance :residual]))))

(defn- check-weights
  "3.1.14."
  [weights ref]
  (t/is (v/delta-eq (:weights weights) (:weights ref)))
  (t/is (v/delta-eq (:initial weights) (:initial ref))))

(defn- check-analysis-residuals-glm
  "3.1.15."
  [residuals ref]
  (t/is (v/delta-eq (:studentized residuals) (:studentized ref)))
  (t/is (v/delta-eq (get-in residuals [:standardized :deviance]) (get-in ref [:standardized :deviance])))
  (t/is (v/delta-eq (get-in residuals [:standardized :pearson]) (get-in ref [:standardized :pearson]))))

(defn- check-dose
  "3.1.16."
  [dose ref]
  (t/is (m/delta-eq (:dose dose) (:dose ref)))
  (t/is (m/delta-eq (:stderr dose) (:stderr ref))))

(defn- check-quantile-residuals
  "3.1.19."
  [qres ref]
  (t/is (v/delta-eq qres ref)))

(defn- glm-tests
  "§3.3. `ref-block` is an already-resolved {:model :analysis :extra} map.
  Dose is checked whenever fastmath's own fitted model has >1 coefficient AND
  the reference carries a (non-error) dose block -- mirrors the generator's
  own `(when (> (count (:coefficients model)) 1) ...)` gate exactly (fixing
  the original R-based `glm-tests`' `:coefficeints` typo, which had made its
  own dose comparison permanently vacuous)."
  ([ys xss ref-block] (glm-tests ys xss nil ref-block))
  ([ys xss options ref-block]
   (let [glm (sut/glm ys xss (merge {:epsilon 1.0e-16 :max-iters 100} options))
         analysis (sut/analysis glm)]
     (t/is (m/delta-eq (:intercept glm) (get-in ref-block [:model :intercept])))
     (t/is (v/delta-eq (:beta glm) (get-in ref-block [:model :beta])))
     (check-coefficients (:coefficients glm) (get-in ref-block [:model :coefficients]))
     (check-xtxinv (:xtxinv glm) (get-in ref-block [:model :xtxinv]))
     (check-df (:df glm) (get-in ref-block [:model :df]))
     (when-not (:no-ll? options)
       (check-ll (:ll glm) (get-in ref-block [:model :ll])))
     (check-fit-glm glm (:model ref-block))
     (when (:compare-deviance-null? options)
       (t/is (m/delta-eq (get-in glm [:deviance :null]) (get-in ref-block [:model :deviance :null]))))
     (check-residuals-glm (:residuals glm) (get-in ref-block [:model :residuals]))
     (check-weights (:weights glm) (get-in ref-block [:model :weights]))
     (when-not (:no-analysis? options)
       (check-correlation (:correlation analysis) (get-in ref-block [:analysis :correlation]))
       (check-analysis-residuals-glm (:residuals analysis) (get-in ref-block [:analysis :residuals]))
       (check-leverage (:leverage analysis) (get-in ref-block [:analysis :leverage]))
       (check-influence (:influence analysis) (get-in ref-block [:analysis :influence]) 1.0e-5))
     (when (> (count (:coefficients glm)) 1)
       (let [dose-ref (get-in ref-block [:extra :dose])]
         (when (and dose-ref (not (:error dose-ref)))
           (check-dose (sut/dose glm) dose-ref))))
     (when-let [qres-ref (get-in ref-block [:extra :quantile-residuals])]
       (check-quantile-residuals (sut/quantile-residuals glm) qres-ref))
     (when-let [predict-ref (get-in ref-block [:extra :predict])]
       (check-predict glm (:newdata-xss options) predict-ref)))))

(t/deftest dummy-data
  (let [ref (load-ref "dummy-data")]
    (glm-tests nys xss {:weights weights :family :binomial :newdata-xss new-xss} (:call-0 ref))
    (glm-tests nys xss {:weights weights :family :binomial :link :probit :newdata-xss new-xss} (:call-1 ref))
    (glm-tests nys xss {:weights weights :family :binomial :link :cloglog :newdata-xss new-xss} (:call-2 ref))
    (glm-tests nys xss {:weights weights :family :binomial :link :log :newdata-xss new-xss} (:call-3 ref))
    (glm-tests nys xss {:family :binomial :newdata-xss new-xss} (:call-4 ref))
    (glm-tests nys xss {:family :binomial :link :probit :newdata-xss new-xss} (:call-5 ref))
    (glm-tests nys xss {:family :binomial :link :cloglog :newdata-xss new-xss} (:call-6 ref))
    (glm-tests nys xss {:family :binomial :link :log :newdata-xss new-xss} (:call-7 ref))
    (glm-tests nys xss {:weights weights :family :binomial :intercept? false :newdata-xss new-xss} (:call-8 ref))
    (glm-tests nys xss {:weights weights :family :binomial :link :probit :intercept? false :newdata-xss new-xss}
                   (:call-9 ref))
    (glm-tests nys xss {:weights weights :family :binomial :link :cloglog :intercept? false :newdata-xss new-xss}
                   (:call-10 ref))
    (glm-tests nys xss {:family :binomial :intercept? false :newdata-xss new-xss} (:call-11 ref))
    (glm-tests nys xss {:family :binomial :link :probit :intercept? false :newdata-xss new-xss} (:call-12 ref))
    (glm-tests nys xss {:family :binomial :link :cloglog :intercept? false :newdata-xss new-xss} (:call-13 ref))
    (glm-tests nys xss {:family :binomial :transformer (fn [[a b c]] [(m/exp a) a b c]) :newdata-xss new-xss}
                   (:call-14 ref))))

(t/deftest gaussian-glm
  (let [ref (load-ref "gaussian-glm")]
    (glm-tests ys xss {:weights weights :newdata-xss new-xss} (:call-0 ref))
    (glm-tests ys xss {:weights weights :offset offset :newdata-xss (with-new-offset)} (:call-1 ref))
    (glm-tests ys xss {:weights weights :intercept? false :newdata-xss new-xss} (:call-2 ref))
    (glm-tests ys xss {:weights weights :intercept? false :offset offset :newdata-xss (with-new-offset)}
                   (:call-3 ref))
    (glm-tests ys xss {:newdata-xss new-xss} (:call-4 ref))
    (glm-tests ys xss {:offset offset :newdata-xss (with-new-offset)} (:call-5 ref))
    (glm-tests ys xss {:intercept? false :newdata-xss new-xss} (:call-6 ref))
    (glm-tests ys xss {:intercept? false :offset offset :newdata-xss (with-new-offset)} (:call-7 ref))))

(t/deftest gestation-data
  (let [ref (load-ref "gestation-data")
        {:keys [Weight Age Births]} (get-in ref [:inputs :columns])
        new-age [26.0 40.0]]
    (lm-tests Weight Age {:weights Births :newdata-xss new-age} (:call-0 ref))
    (lm-tests Weight Age {:newdata-xss new-age} (:call-1 ref))))

(t/deftest lungcap-data
  (let [ref (load-ref "lungcap-data")
        {:keys [FEV Age Ht Gender Smoke]} (get-in ref [:inputs :columns])
        logfev (mapv m/log FEV)
        gender-numeric (mapv #(if (= % :F) 0.0 1.0) Gender)
        {gender-f :F gender-m :M} (one-hot Gender [:F :M])
        ht-smoke (mapv * Ht Smoke)
        ;; new (Age, Ht, Gender, Smoke) rows, matching regression-ref-gen exactly
        new-age [8.0 15.0] new-ht [55.0 65.0]
        new-gender-numeric [0.0 1.0] new-gender-f [1.0 0.0] new-gender-m [0.0 1.0]
        new-smoke [0.0 1.0]
        new-ht-smoke (mapv * new-ht new-smoke)]
    (lm-tests logfev (map vector Age Ht gender-numeric Smoke)
                  {:newdata-xss (map vector new-age new-ht new-gender-numeric new-smoke)} (:call-0 ref))
    (lm-tests logfev (map vector Age Ht gender-f gender-m Smoke)
                  {:intercept? false
                   :newdata-xss (map vector new-age new-ht new-gender-f new-gender-m new-smoke)} (:call-1 ref))
    (lm-tests logfev (map vector Ht gender-numeric Smoke)
                  {:newdata-xss (map vector new-ht new-gender-numeric new-smoke)} (:call-2 ref))
    (lm-tests logfev (map vector gender-numeric Smoke)
                  {:newdata-xss (map vector new-gender-numeric new-smoke)} (:call-3 ref))
    (lm-tests logfev (map vector Age Smoke) {:newdata-xss (map vector new-age new-smoke)} (:call-4 ref))
    (lm-tests logfev (map vector Ht Smoke) {:newdata-xss (map vector new-ht new-smoke)} (:call-5 ref))
    (lm-tests logfev (map vector Ht Smoke ht-smoke)
                  {:newdata-xss (map vector new-ht new-smoke new-ht-smoke)} (:call-6 ref))))

(t/deftest dental-data
  (let [ref (load-ref "dental-data")
        {:keys [DMFT Sugar Indus]} (get-in ref [:inputs :columns])
        indus-bin (mapv #(if (= % :Ind) 0.0 1.0) Indus)
        sugar-indus (mapv * Sugar indus-bin)
        ;; new (Sugar, Indus) rows: Sugar=[10,50], Indus=[Ind,NonInd]
        new-sugar [10.0 50.0]
        new-indus-bin [0.0 1.0]
        new-sugar-indus (mapv * new-sugar new-indus-bin)
        new-xss (map vector new-sugar new-indus-bin new-sugar-indus)]
    (lm-tests DMFT (map vector Sugar indus-bin sugar-indus) {:newdata-xss new-xss} ref)))

(t/deftest cheese-data
  (let [ref (load-ref "cheese-data")
        {:keys [Taste Acetic H2S Lactic]} (get-in ref [:inputs :columns])
        lH2S (mapv m/log H2S)
        acetic-lH2S (mapv * Acetic lH2S)
        acetic-lactic (mapv * Acetic Lactic)
        lH2S-lactic (mapv * lH2S Lactic)
        triple (mapv * Acetic lH2S Lactic)
        ;; new (Acetic, H2S, Lactic) rows, matching regression-ref-gen exactly
        new-acetic [300.0 150.0]
        new-h2s [5000.0 100.0]
        new-lactic [1.3 1.0]
        new-lh2s (mapv m/log new-h2s)
        new-xss (map vector new-acetic new-lh2s new-lactic
                     (mapv * new-acetic new-lh2s) (mapv * new-acetic new-lactic) (mapv * new-lh2s new-lactic)
                     (mapv * new-acetic new-lh2s new-lactic))]
    (lm-tests Taste (map vector Acetic lH2S Lactic acetic-lH2S acetic-lactic lH2S-lactic triple)
                  {:newdata-xss new-xss} ref)))

(t/deftest turbunes-data
  (let [ref (load-ref "turbunes-data")
        {:keys [Fissures Turbines Hours]} (get-in ref [:inputs :columns])
        ratio (mapv / Fissures Turbines)
        turb-fiss-diff (mapv - Turbines Fissures)
        new-hours [1000.0 3000.0]]
    (glm-tests ratio Hours {:family :binomial :weights Turbines :newdata-xss new-hours} (:call-0 ref))
    (glm-tests (mapv vector Fissures turb-fiss-diff) Hours {:family :binomial :newdata-xss new-hours} (:call-1 ref))
    (glm-tests ratio Hours {:family :binomial :weights Turbines :link :probit :newdata-xss new-hours} (:call-2 ref))
    (glm-tests ratio Hours {:family :binomial :weights Turbines :link :cloglog :newdata-xss new-hours}
                   (:call-3 ref))))

(t/deftest germ-data
  (let [ref (load-ref "germ-data")
        {:keys [Germ Total Seeds Extract]} (get-in ref [:inputs :columns])
        seeds-oa75 (mapv #(if (= % :OA75) 1.0 0.0) Seeds)
        extract-cucumber (mapv #(if (= % :Cucumber) 1.0 0.0) Extract)
        es (mapv * extract-cucumber seeds-oa75)
        ratio (mapv / Germ Total)
        ;; new (Seeds, Extract) rows: [OA75,Cucumber] and [OA73,Bean]
        new-seeds-oa75 [1.0 0.0]
        new-extract-cucumber [1.0 0.0]
        new-es (mapv * new-seeds-oa75 new-extract-cucumber)
        new-xss-2 (map vector new-seeds-oa75 new-extract-cucumber)
        new-xss-3 (map vector new-seeds-oa75 new-extract-cucumber new-es)]
    (glm-tests ratio (mapv vector seeds-oa75 extract-cucumber)
                   {:family :binomial :weights Total :newdata-xss new-xss-2} (:call-0 ref))
    (glm-tests ratio (mapv vector seeds-oa75 extract-cucumber es)
                   {:family :binomial :weights Total :newdata-xss new-xss-3} (:call-1 ref))
    (glm-tests ratio (mapv vector seeds-oa75 extract-cucumber es)
                   {:family :quasi-binomial :weights Total :no-ll? true :newdata-xss new-xss-3} (:call-2 ref))))

(t/deftest mammary-data
  (let [ref (load-ref "mammary-data")
        columns (get-in ref [:inputs :columns])
        n-outgrowths (:N.Outgrowths columns)
        n-assays (:N.Assays columns)
        n-cells (:N.Cells columns)
        ratio (mapv / n-outgrowths n-assays)
        lncells (mapv m/log n-cells)
        ;; new N.Cells=[50,90] (offset source)/N.Outgrowths=[5,10]
        new-loffset (mapv m/log [50.0 90.0])
        new-nout [5.0 10.0]]

    ;; only intercept and offset
    (glm-tests ratio :intercept {:family :binomial :link :cloglog
                                     :weights n-assays :offset lncells
                                     :newdata-xss (map vector new-loffset)}
                   (:call-0 ref))

    ;; intercept, offset, data point
    (glm-tests ratio n-outgrowths {:family :binomial :link :cloglog
                                       :weights n-assays :offset lncells
                                       :newdata-xss (map vector new-loffset new-nout)}
                   (:call-1 ref))

    ;; no intercept, offset, data point
    (glm-tests ratio n-outgrowths {:family :binomial :link :cloglog
                                       :weights n-assays :offset lncells
                                       :intercept? false :compare-deviance-null? false
                                       :newdata-xss (map vector new-loffset new-nout)}
                   (:call-2 ref))

    (glm-tests ratio lncells {:family :binomial :link :cloglog :weights n-assays
                                  :newdata-xss new-loffset}
                   (:call-3 ref))))

(t/deftest deposit-data
  (let [ref (load-ref "deposit-data")
        {:keys [Killed Number Deposit Insecticide]} (get-in ref [:inputs :columns])
        ratio (mapv / Killed Number)
        logdep (mapv m/log Deposit)
        {ins-a :A ins-b :B ins-c :C} (one-hot Insecticide [:A :B :C])
        ;; `sut/polynomial-transformer`, wrapped to poly-expand only the
        ;; log(Deposit) slot and pass the two Insecticide dummies through --
        ;; supersedes the old `add-poly`-based pre-expanded-columns approach
        ;; (see §2.4 above); unlike it, this is a genuine fitted closure
        ;; usable on *new* Deposit values, hence call-3's own newdata check below.
        poly-transformer (sut/polynomial-transformer logdep 2)
        deposit-poly-transformer (fn [[ld insb insc]] (into (poly-transformer [ld]) [insb insc]))
        model (sut/glm ratio (map vector Deposit ins-b ins-c) {:family :binomial :weights Number})
        model2 (sut/glm ratio (map vector Deposit ins-a ins-b ins-c)
                        {:family :binomial :weights Number :intercept? false})
        newdata (get-in ref [:extra :newdata])]
    (glm-tests ratio (map vector Deposit ins-b ins-c) {:family :binomial :weights Number} (:call-0 ref))
    (glm-tests ratio (map vector Deposit ins-a ins-b ins-c)
                   {:family :binomial :weights Number :intercept? false} (:call-1 ref))
    (glm-tests ratio (map vector logdep ins-a ins-b ins-c)
                   {:family :binomial :weights Number :intercept? false} (:call-2 ref))
    (t/is (v/delta-eq (map model (map vector newdata (repeat 0) (repeat 0)))
                      (get-in ref [:extra :predict-a :fit])))
    (t/is (v/delta-eq (map model (map vector newdata (repeat 1) (repeat 0)))
                      (get-in ref [:extra :predict-b :fit])))
    (t/is (v/delta-eq (map model (map vector newdata (repeat 0) (repeat 1)))
                      (get-in ref [:extra :predict-c :fit])))
    ;; stderr/confidence-interval, upgraded from the original bare-fit-only check
    (doseq [[level repeat0 repeat1] [[:predict-a (repeat 0) (repeat 0)]
                                      [:predict-b (repeat 1) (repeat 0)]
                                      [:predict-c (repeat 0) (repeat 1)]]
            :let [preds (map #(model % true) (map vector newdata repeat0 repeat1))
                  ref-block (get-in ref [:extra level])]]
      (t/is (v/delta-eq (map :stderr preds) (:stderr ref-block)))
      (t/is (v/delta-eq (mapcat :confidence-interval preds) (flatten (:confidence-interval ref-block)))))
    (t/are [id v] (v/delta-eq (:dose (sut/dose model2 0.5 id 0)) v)
      1 5.099708
      2 4.514714
      3 0.8443372)
    (glm-tests ratio (map vector logdep ins-b ins-c)
                   {:family :binomial :weights Number :transformer deposit-poly-transformer
                    :newdata-xss (get-in ref [:call-3 :extra :newdata-xss])}
                   (:call-3 ref))))

;; poisson

(t/deftest danishlc-data
  (let [ref (load-ref "danishlc-data")
        {:keys [Cases Pop Age City AgeNum]} (get-in ref [:inputs :columns])
        loffset (v/log (seq Pop))
        {:keys [xss]} (mult-columns City Age)
        {age-5559 :55-59 age-6064 :60-64 age-6569 :65-69 age-7074 :70-74 age-gt74 :>74}
        (one-hot Age [:55-59 :60-64 :65-69 :70-74 :>74])
        age-xss (map vector age-5559 age-6064 age-6569 age-7074 age-gt74)
        ;; supersedes `add-poly` (§2.4 above) -- a fitted `:transformer`
        ;; closure, applied to the raw `AgeNum` column (like call-2's own xss)
        poly-transformer (sut/polynomial-transformer AgeNum 2)]
    ;; df = 0
    (glm-tests Cases xss {:family :poisson :offset loffset :no-analysis? true
                              :newdata-xss (get-in ref [:call-0 :extra :newdata-xss])} (:call-0 ref))
    (glm-tests Cases age-xss {:family :poisson :offset loffset
                                  :newdata-xss (get-in ref [:call-1 :extra :newdata-xss])} (:call-1 ref))
    (glm-tests Cases AgeNum {:family :poisson :offset loffset
                                 :newdata-xss (get-in ref [:call-2 :extra :newdata-xss])} (:call-2 ref))
    (glm-tests Cases AgeNum {:family :poisson :offset loffset :transformer poly-transformer
                                 :newdata-xss (get-in ref [:call-3 :extra :newdata-xss])} (:call-3 ref))))


(t/deftest counts2x2-data
  (let [ref (load-ref "counts2x2-data")
        {:keys [Counts Att Inc]} (get-in ref [:inputs :columns])
        {att-against :Against} (one-hot Att [:Against])
        {inc-low :Low} (one-hot Inc [:Low])
        att-inc-low (mapv * att-against inc-low)]
    (glm-tests Counts (map vector att-against inc-low)
                   {:family :poisson :no-analysis? true
                    :newdata-xss (get-in ref [:call-0 :extra :newdata-xss])} (:call-0 ref))
    (glm-tests Counts (map vector att-against inc-low att-inc-low)
                   {:family :poisson :no-analysis? true
                    :newdata-xss (get-in ref [:call-1 :extra :newdata-xss])} (:call-1 ref))
    (glm-tests att-against inc-low {:family :binomial :weights Counts
                                        :newdata-xss (get-in ref [:call-2 :extra :newdata-xss])} (:call-2 ref))))

(t/deftest kstones-data
  (let [ref (load-ref "kstones-data")
        {:keys [Counts Size Method Outcome]} (get-in ref [:inputs :columns])
        {size-small :Small} (one-hot Size [:Small])
        {method-b :B} (one-hot Method [:B])
        {outcome-success :Success} (one-hot Outcome [:Success])
        size-method (mapv * size-small method-b)
        size-outcome (mapv * size-small outcome-success)
        method-outcome (mapv * method-b outcome-success)
        size-method-outcome (mapv * size-small method-b outcome-success)]
    (glm-tests Counts (map vector size-small method-b outcome-success)
                   {:family :poisson :newdata-xss (get-in ref [:call-0 :extra :newdata-xss])} (:call-0 ref))
    (glm-tests Counts (map vector size-small method-b outcome-success size-method)
                   {:family :poisson :newdata-xss (get-in ref [:call-1 :extra :newdata-xss])} (:call-1 ref))
    (glm-tests Counts (map vector size-small outcome-success method-b size-outcome)
                   {:family :poisson :newdata-xss (get-in ref [:call-2 :extra :newdata-xss])} (:call-2 ref))
    (glm-tests Counts (map vector outcome-success method-b size-small method-outcome)
                   {:family :poisson :newdata-xss (get-in ref [:call-3 :extra :newdata-xss])} (:call-3 ref))
    (glm-tests Counts (map vector size-small method-b outcome-success size-method size-outcome)
                   {:family :poisson :newdata-xss (get-in ref [:call-4 :extra :newdata-xss])} (:call-4 ref))
    (glm-tests Counts (map vector method-b outcome-success size-small method-outcome size-method)
                   {:family :poisson :newdata-xss (get-in ref [:call-5 :extra :newdata-xss])} (:call-5 ref))
    (glm-tests Counts (map vector outcome-success method-b size-small method-outcome size-outcome)
                   {:family :poisson :newdata-xss (get-in ref [:call-6 :extra :newdata-xss])} (:call-6 ref))
    (glm-tests Counts (map vector size-small method-b outcome-success size-method size-outcome method-outcome)
                   {:family :poisson :no-analysis? true
                    :newdata-xss (get-in ref [:call-7 :extra :newdata-xss])} (:call-7 ref))
    (glm-tests Counts (map vector size-small method-b outcome-success size-method size-outcome method-outcome
                                size-method-outcome)
                   {:family :poisson :no-analysis? true
                    :newdata-xss (get-in ref [:call-8 :extra :newdata-xss])} (:call-8 ref))
    (glm-tests outcome-success (map vector size-small method-b size-method)
                   {:family :binomial :weights Counts
                    :newdata-xss (get-in ref [:call-9 :extra :newdata-xss])} (:call-9 ref))))

(t/deftest pock-data
  (let [ref (load-ref "pock-data")
        {:keys [Count Dilution]} (get-in ref [:inputs :columns])
        l2dilution (mapv #(/ (m/log %) (m/log 2.0)) Dilution)
        new-l2dilution (mapv #(/ (m/log %) (m/log 2.0)) [4.0 10.0])]
    (glm-tests Count l2dilution {:family :poisson :newdata-xss new-l2dilution} (:call-0 ref))
    (glm-tests Count l2dilution {:family :quasi-poisson :no-ll? true :newdata-xss new-l2dilution} (:call-1 ref))
    (glm-tests Count l2dilution {:family :nbinomial :nbinomial-theta 9.892894299757403
                                     :newdata-xss new-l2dilution} (:call-2 ref))
    (t/is (m/delta-eq (get-in ref [:extra :nbinomial-theta])
                      (:nbinomial-theta (sut/glm-nbinomial Count l2dilution))))))

(t/deftest hcrabs-data
  (let [ref (load-ref "hcrabs-data")
        {:keys [Sat Wt Width Spine Col]} (get-in ref [:inputs :columns])
        logwt (mapv m/log Wt)
        logwidth (mapv m/log Width)
        {spine-noneok :NoneOK spine-oneok :OneOK} (one-hot Spine [:NoneOK :OneOK])
        {col-dm :DM col-lm :LM col-m :M} (one-hot Col [:DM :LM :M])
        full-xss (map vector logwt logwidth spine-noneok spine-oneok col-dm col-lm col-m)]
    (glm-tests Sat full-xss {:family :quasi-poisson :no-ll? true
                                 :newdata-xss (get-in ref [:call-0 :extra :newdata-xss])} (:call-0 ref))
    (glm-tests Sat logwt {:family :quasi-poisson :no-ll? true
                              :newdata-xss (get-in ref [:call-1 :extra :newdata-xss])} (:call-1 ref))
    (glm-tests Sat logwt {:family :nbinomial :nbinomial-theta 0.9580286019527684
                              :newdata-xss (get-in ref [:call-2 :extra :newdata-xss])} (:call-2 ref))
    (t/is (m/delta-eq (get-in ref [:extra :nbinomial-theta])
                      (:nbinomial-theta (sut/glm-nbinomial Sat logwt))))))

(t/deftest lime-data
  (let [ref (load-ref "lime-data")
        {:keys [Foliage DBH Origin]} (get-in ref [:inputs :columns])
        logdbh (mapv m/log DBH)
        {origin-natural :Natural origin-planted :Planted} (one-hot Origin [:Natural :Planted])
        origin-natural-logdbh (mapv * origin-natural logdbh)
        origin-planted-logdbh (mapv * origin-planted logdbh)
        xss (map vector origin-natural origin-planted logdbh origin-natural-logdbh origin-planted-logdbh)
        new-xss (get-in ref [:call-0 :extra :newdata-xss])]
    (glm-tests Foliage xss {:family :gamma :link :log :newdata-xss new-xss} (:call-0 ref))
    (t/is (v/delta-eq (-> (sut/glm Foliage xss {:family :gamma :link :log})
                          (sut/quantile-residuals))
                      (get-in ref [:call-0 :extra :quantile-residuals]) 5.0e-3))
    (glm-tests Foliage xss {:family :inverse-gaussian :link :log :newdata-xss new-xss} (:call-1 ref))))

(t/deftest perm-data
  (let [ref (load-ref "perm-data")
        {:keys [Perm Mach Day]} (get-in ref [:inputs :columns])
        {:keys [xss]} (mult-columns Mach Day)]
    (glm-tests Perm xss {:family :inverse-gaussian :link :log
                             :newdata-xss (get-in ref [:extra :newdata-xss])} ref)))

(t/deftest yieldden-data
  (let [ref (load-ref "yieldden-data")
        {:keys [YD Dens Var]} (get-in ref [:inputs :columns])
        rdens (mapv #(/ 1.0 %) Dens)
        {var2 :2 var3 :3} (one-hot Var [:2 :3])
        dens-var2 (mapv * Dens var2)
        dens-var3 (mapv * Dens var3)
        rdens-var2 (mapv * rdens var2)
        rdens-var3 (mapv * rdens var3)
        full-xss (map vector Dens rdens var2 var3 dens-var2 dens-var3 rdens-var2 rdens-var3)
        simple-xss (map vector Dens rdens var2 var3)]
    (glm-tests YD full-xss {:family :gamma :link :inverse
                                :newdata-xss (get-in ref [:call-0 :extra :newdata-xss])} (:call-0 ref))
    (glm-tests YD simple-xss {:family :gamma :link :inverse
                                  :newdata-xss (get-in ref [:call-1 :extra :newdata-xss])} (:call-1 ref))
    (t/is (v/delta-eq (-> (sut/glm YD simple-xss {:family :inverse-gaussian})
                          (sut/quantile-residuals))
                      (get-in ref [:extra :quantile-residuals])))))


(t/deftest lm-simplest-case
  (t/testing "Daniel's case"
    (let [model (sut/lm [3 3 5 6] [[1 1] [2 1] [3 2] [4 2]])]
      (t/is (m/delta-eq 4.25 (model [1 2])))))
  (t/testing "1d prediction"
    (let [model (sut/lm [3 3 5 6] [1 2 3 4])]
      (t/is (m/delta-eq 2.6 (model 1)))
      (t/is (m/delta-eq 2.6 (model [1])))))
  (t/testing "1d prediction with offset"
    (let [model (sut/lm [3 3 5 6] [1 2 3 4] {:offset [11 12 13 14]})]
      (t/is (m/delta-eq 2.6 (model [11 1])))
      (t/testing "wrong number of entries on input"
        (t/is (= {:offset? true :expected 1 :received 0} (try (model 1) (catch clojure.lang.ExceptionInfo e (ex-data e)))))
        (t/is (= {:offset? true :expected 1 :received 0} (try (model [1]) (catch clojure.lang.ExceptionInfo e (ex-data e)))))
        (t/is (= {:offset? true :expected 1 :received 2} (try (model [1 2 3]) (catch clojure.lang.ExceptionInfo e (ex-data e)))))))))

;; isotonic

(t/deftest pava
  (t/testing "PAVA algorithm, joinr data"
    (let [data [0.111423005
                0.130146772
                0.160549527
                0.156687074
                0.19867116
                0.124814828
                0.202970037
                0.175093787
                0.160140179
                0.176404285
                0.194732146
                0.134872388
                0.18139233
                0.215037018
                0.149917456
                0.170697662
                0.104128164
                0.116869636]]
      (t/is (v/delta-eq (sut/pava data) [0.111423005
                                         0.130146772
                                         0.1586183005
                                         0.1586183005
                                         0.161742994
                                         0.161742994
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924
                                         0.165187924])))))


(t/deftest cir
  (t/testing "ascending with weights"
    (let [[xs ys] (sut/cir [-1,1,2,3,4,7,8,9,11] [2,1,7,4,5,7,6,9,7] [2,1,2,1,2,11,2,1,5] :asc)]
      (t/is (v/delta-eq xs [ -1.0000000 -0.3333333  3.0000000  7.1538462 10.6666667 11.0000000]))
      (t/is (v/delta-eq ys [1.666667 1.666667 5.600000 6.846154 7.333333 7.333333]))))
  (t/testing "ascending now weights"
    (let [[xs ys] (sut/cir [-1,1,2,3,4,7,8,9,11] [2,1,7,4,5,7,6,9,7])]
      (t/is (v/delta-eq xs [-1.0  0.0  3.0  7.5 10.0 11.0]))
      (t/is (v/delta-eq ys [ 1.500000 1.500000 5.333333 6.500000 8.000000 8.000000]))))
  (t/testing "python example"
    (let [[xs ys] (sut/cir [1 2 3 4] [1, 37, 42, 5])]
      (t/is (v/delta-eq xs [1 3 4]))
      (t/is (v/delta-eq ys [1 28 28])))))

(t/deftest with-offset
  (t/is (= [1 [2 3]] (sut/with-offset [1 2 3] true)))
  (t/is (= [0.0 [1 2 3]] (sut/with-offset [1 2 3] false)))
  (t/is (= [0.0 [1 2 :d]] (sut/with-offset '(1 2 :d) false)))
  (t/is (= [1 [2 :d]] (sut/with-offset '(1 2 :d) true)))
  (t/is (= [0.0 [:a :b]] (sut/with-offset [:a :b] false)))
  (t/testing "exception when offset is not a number"
    (t/is (= :z (try (sut/with-offset [:z 1 2] true) (catch clojure.lang.ExceptionInfo e (:offset (ex-data e))))))))
